- vue/components/ui/footer-platforme/footer-platforme.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Fix anchor style of footer in accordance to pulse's footer.  |
| Animated GIF | Below  |
> Fix desktop's footer anchor style

- webpack.config.js
As @3rdvision found out, it seems that the upgrade of `url-loader` to `3.0.0` [needs tuning](https://github.com/vuejs/vue-loader/issues/1612#issuecomment-559366730) to work with `vue-loader`.
> Fix URL loader usage

- vue/components/ui/listing-platforme/listing-platforme.vue
Problem:
* Listing was receiving a slot named 'item'
* Expected: pass a **new** 'item' slot to Filtering
* Actual: pass the original 'item' slot
* Observed problem: adding filters by clicking on items on the `order-list` from Pulse didn't work
> Fix listing usage of slots

- vue/components/ui/tabs-platforme/tabs-platforme.vue
| - | - |
| --- | --- |
| Issue | The current tab's buttons alignment are subjective to father styles alignments, like for example `body` tag with class `desktop` that forces the alignment to be set to `center`|
| Decisions | Force the correct behaviour by writing on the component it self the correct alignment |
> Fix text alignment on the tabs elements

- vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Issue | When mouse hovers over a button, the border color is different from the background color. |
> Fix button hover colors

- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Below |
| Animated GIF | ![5l7kPTJZpy](https://user-images.githubusercontent.com/24736423/71575631-942bd780-2ae5-11ea-8fad-d14a69f408e2.gif)  |
When a user adds the first filter after landing on a page it will set the search input text field  to `"undefined<filter>"` instead of just `"<filter>"`.
This is because `this.context.filter` is undefined at the `created` vue instance moment therefore, as result, when `addFilter()` is called, `"undefined"` will concatenate to the value of `this.filter`.
Reproducible in any listing containing filters, for instance https://ripe-pulse-sbx.platforme.com/orders.
1 - Open https://ripe-pulse-sbx.platforme.com/orders;
2- Click a filter.
Undesired effect: `"undefined[...]"` will appear in the search …
> Fix undefined filter

- vue/components/ui/atoms/link/link.vue
Default hover had support for the "hover" class but the remaining colors didn't. Fixed that.
> Fixed hover class

- vue/components/ui/atoms/input/input.vue
| - | - |
| --- | --- |
| Issue | Vue displays error in console if the prop `value` is a Number. This _small change_ spares the job of having to convert types when passing a numeric `value` to `input-ripe`. |
> Fix input value type

- vue/components/ui/atoms/attachments/attachments.stories.js
- vue/components/ui/atoms/attachments/attachments.vue
| - | - |
| --- | --- |
| Issue |  |
| Decisions | Attachments with long names are now displayed correctly and the user now sees the attachment name when hovering with the mouse on top of the attachment in the list of attachments.  |
| Animated GIF | **Before:** ![attachments_before](https://user-images.githubusercontent.com/22588915/71816644-2ea69080-307b-11ea-8805-762975da57a4.gif) **After:** ![attachments_after](https://user-images.githubusercontent.com/22588915/71816643-2ea69080-307b-11ea-8f5f-21cddf29a453.gif) |
> Fixed "attachments" long names + Shows attachment name on hover

- vue/components/ui/molecules/chat-message/chat-message.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | No more warnings relative to the conflict between attachments with the same name. |
> Fixed attachments names conflict warning

- vue/components/ui/atoms/dropdown/dropdown.vue
- vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | Missing z-index in the component ending up with components on top of this one. |
| Decisions |   Added z-index property |
| Animated GIF | <img width="422" alt="Screenshot 2020-01-06 at 12 26 02" src="https://user-images.githubusercontent.com/13239857/71818304-8398d580-3080-11ea-8fd5-29be6472307c.png"> |
> Missing z-index in the select

- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | There is a negative margin in the detail component header buttons creating a misalignment  with the title |
| Decisions | Removed that negative margin |
| Animated GIF |  ![ezgif com-gif-maker](https://user-images.githubusercontent.com/13239857/72245300-22c14e00-35e8-11ea-9a5e-7dc372528516.gif) |
> Removed negative margin

- vue/components/ui/molecules/search/search.stories.js
- vue/components/ui/molecules/search/search.vue
| - | - |
| --- | --- |
| Issue |- |
| Decisions |  Added delete button that appears when there is text in the search bar. When pressed, all that text is deleted. |
| Animated GIF | ![search_delete_button](https://user-images.githubusercontent.com/22588915/71911794-4ad62a80-316c-11ea-87ad-ef68d87299e5.gif) |
> Added delete button to "search" component

- vue/components/ui/molecules/lightbox/lightbox.vue
- vue/components/ui/molecules/table/table.custom.stories.js
- vue/components/ui/molecules/table/table.vue
Use case: allowing extra info to appear below a row after a click (e.g.: order activity chat on RIPE Pulse).
> Add table extra-row slot

- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | Props from component details required the item to exist from the start. But this creates an error in the majority of cases where we have a parent still requesting the item itself. |
| Decisions |  Remove the required from props so that no error appear. <br> It was  tested in the pulse project -> order show component by forcing the data request to always return null. No bugs where found in the UI or console logs. |
> Changed Details item prop required to false

- vue/components/ui/atoms/input/input.stories.js
- vue/components/ui/atoms/input/input.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | As suggested in a PR's comment https://github.com/ripe-tech/ripe-components-vue/pull/168#discussion_r365787877, `text-overflow: ellipsis` should be default in `input-ripe`. |
| Animated GIF | <img width="434" alt="imagem" src="https://user-images.githubusercontent.com/24736423/72258338-b3f2ed80-3605-11ea-802e-81f65f710063.png"> |
> Add ellipsis to input-ripe

- vue/components/ui/organisms/listing/listing.stories.js
| - | - |
| --- | --- |
| Issue | Header wasn't showing in the listing story. Prop naming was outdated. |
| Decisions | Updated listing story with the new prop naming. |
> Fix listing story header

- vue/components/ui/atoms/input/input.stories.js
- vue/components/ui/atoms/input/input.vue
- vue/components/ui/molecules/input-symbol/input-symbol.vue
| - | - |
| --- | --- |
| Issue | When we pass a width prop lower than 203 to `input-symbol`, it doesn't size as it should. This is because input has a default browser's `width` and flexbox's `min-width: auto`. This can be solved by overriding the behavior  with `min-width: 0px`.  Further details at: https://stackoverflow.com/a/42421490   |
| Decisions |   |
| Animated GIF | Below  |
`width = 100`
**Note:** Border in blue doesn't display correctly and the width of the element is not 100px but 100 + 24px.
`width = 100`
> Fix input min width bug

- vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Issue | When a table row is clicked, `table-ripe` emits a click event `$emit("click", item, index)`, and is expected that the payload of that event is the clicked item and the item's index position in the `items` passed as prop. Instead, it is emiting the position index in the table. This is a problem when the table has different a orientation than the original when sorted and/or reversed. With this fix `$emit("click", item, index)` will emit in the click event, the clicked item and the respective item's index. |
| Decisions |   |
> Fix table item click index

- vue/components/ui/molecules/lineup/lineup.stories.js
| - | - |
| --- | --- |
| Issue | Lineup story using value instead of field |
| Decisions | Changed value to field |
> Fix lineup story "value" into "field"

- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | When listing has `button-icons`, `scroll-icon` doesn't correctly overlap. Mouse click and hover effect don't work as expected. |
| Decisions |   |
> Fix scroll-button interference

- vue/components/ui/atoms/checkbox/checkbox.vue
- vue/components/ui/molecules/checkbox-group/checkbox-group.vue
| - | - |
| --- | --- |
| Issue | `index` and `value` variables are no longer in use when emitting updates in the checkbox component: . Checkbox group also suffers from old variables such as `value` still in use.  |
> Fix checkbox changes

- vue/components/ui/atoms/checkbox/checkbox.vue
| - | - |
| --- | --- |
| Issue | When the checkbox was checked and active, the background color was off. ![Feb-05-2020 12-45-49](https://user-images.githubusercontent.com/25725586/73843026-af40e400-4815-11ea-8154-b20b0e1467be.gif)|
| Decisions | Style for checked and active.  |
| Animated GIF | After fix: ![Feb-05-2020 12-46-07](https://user-images.githubusercontent.com/25725586/73843062-c8499500-4815-11ea-9812-9baeb7cb5884.gif) |
> Fix checkbox active style

- vue/components/ui/organisms/details/details.stories.js
- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Header buttons can now be hidden by a prop |
| Animated GIF | ![details-ripe_hide_header_buttons_2](https://user-images.githubusercontent.com/22588915/74731718-7dca0e80-5240-11ea-9c6d-0ca721510eb2.gif) |
> Added prop to allow to hide the header buttons

- vue/components/ui/atoms/dropdown/dropdown.vue
- vue/components/ui/molecules/button-dropdown/button-dropdown.vue
- vue/components/ui/molecules/select/select.vue
Fixes the issue that resulted in opening a dropdown not closing the one previously open.
> Let click events propagate

- vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Issue | The default `type` attribute of the `button` in `button-color` component should be `button` and not `submit` which is the current default attribute value caused by `type` property being null (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button). |
| Decisions |   |
> Fix default type of button-color

- vue/components/ui/molecules/input-currency/input-currency.vue
| - | - |
| --- | --- |
| Issue | When component `input-currency` exists inside a `<form>` HTML5 will validate the number and reject any float number. Float numbers would need `step="any"` which would need `lang="en"` to use dots instead of commas. It might be better to just change the type to text. |
| Animated GIF | <img width="277" alt="imagem" src="https://user-images.githubusercontent.com/24736423/75536716-a0f97880-5a0d-11ea-8c41-eb165f23c981.png"> |
> Fix input type

- vue/components/ui/atoms/button-icon/button-icon.vue
- vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | • Fixed `button-icon `loading animation scale <br> • FIxed `button-icon` width issue when the `button-icon` had text |
| Animated GIF | ![Components-button-icon_loading_fix](https://user-images.githubusercontent.com/22588915/81428081-a4b72300-9153-11ea-93ff-cda8ef031997.gif) |
> Button icon fixes

- vue/components/ui/atoms/button-icon/button-icon.vue
| - | - |
| --- | --- |
| Issue | Bad change in https://github.com/ripe-tech/ripe-components-vue/pull/298/commits/2b5bec21365a87673a37869328e66f4ad16617a2 |
| Decisions | The `margin` applied in the `loaderStyle` was to fix the problem of the "ball-clip-rotate" animation not being centered giving the visual artifact that can be seen below |
| Animated GIF | **Before bad change fix:**<br>![Components-button-icon_fix_bad_change](https://user-images.githubusercontent.com/22588915/81557339-b5e67680-9383-11ea-95aa-3c7bb690e378.gif)<br><br> **After bad change fix:**<br>![Components-button-icon_fix_bad_change_fix](https://user-images.githubusercontent.com/22588915/81557326-b0892c00-9383-11ea-8ac2-b2786a12ab7f.gif) |
> Fix bad change

- vue/assets/icons/extra/options.svg
- vue/components/ui/atoms/icon/icon.vue
| - | - |
| --- | --- |
| Issue | Needed "options" icon to be in `icons` component to be able to better refactor `details-ripe` |
| Decisions | • Support the addition of new icons in the "extra" folder <br>• Added "options" icon (obtained from `details-ripe` asset folder |
| Animated GIF | ![Components-icon_extra_options](https://user-images.githubusercontent.com/22588915/81587758-65850e00-93af-11ea-96bd-4d238ac4f124.gif)<br><br>**Its the same used by `details-ripe`:**<br>![May-11-2020 14-31-32](https://user-images.githubusercontent.com/22588915/81587908-9e24e780-93af-11ea-821f-63a096649f19.gif) |
> Extra icons support

- vue/components/ui/atoms/button-icon/button-icon.stories.js
- vue/components/ui/atoms/button-icon/button-icon.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Can now manually control the `button-icon` `active` state, useful in cases like a dropdown, where we want to set the `button-icon` as active as long as the dropdown is open |
| Animated GIF |  ![Components-button-icon_active_via_prop](https://user-images.githubusercontent.com/22588915/81567577-69576700-9394-11ea-8f43-36c9cbbe7be2.gif)<br>**E.g. Useful when using with dropdowns:**<br>![May-11-2020 14-31-32](https://user-images.githubusercontent.com/22588915/81567818-c7844a00-9394-11ea-91de-9df2222bd17c.gif) |
> Manually control "button-icon" "active" state

- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | Fix header-button to copy the link not hiding when in mobile and tablet mode |
| Dependencies | - |
| Decisions | Hide all header-buttons-before if not in desktop as suggested in https://github.com/ripe-tech/ripe-pulse/pull/126#discussion_r430610318. |
> Hide all header-buttons-before and header-buttons-after in tablet and mobile

- vue/components/ui/molecules/checkbox-group/checkbox-group.vue
| - | - |
| --- | --- |
| Decisions | Makes the default be `{}` instead of `undefined`. |
> Fix default prop

- vue/mixins/clipboard.js
- vue/mixins/index.js
| - | - |
| --- | --- |
| Decisions | Extracted from https://github.com/ripe-tech/ripe-pulse/blob/acca94607519434e58ab0bd53efd96f35aae3866/vue/components/order/order-show/order-show.vue#L924 . This change is needed for unit testing the clipboard (https://github.com/ripe-tech/ripe-pulse/issues/127) |
> Add a clipboard mixin

- vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Decisions | Add missing table CSS, fixing a bad port (https://github.com/ripe-tech/ripe-components-vue/pull/292) |
> Add missing table CSS

- vue/components/ui/organisms/details/details.stories.js
- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | • Added the ability to use `slots` named with the prefix "options-" to change a specific `item` in the options `dropdown` of the `details` component <br>• Improved storybook with an example of the implemented feature |
| Animated GIF | ![Components-Details_options_dropdown_item_slot_support](https://user-images.githubusercontent.com/22588915/84788475-11d99600-afe7-11ea-98b4-bd3b07288066.gif) |
> Change specific items in the options dropdown of the details component

- vue/components/ui/atoms/dropdown/dropdown.vue
| - | - |
| --- | --- |
| Decisions | When adding support for `managed` (https://github.com/ripe-tech/ripe-components-vue/commit/58050938a9e1aebad8af08dedf750027cfe43c73) the default was copied from RIPE White, but in RIPE Pulse it should be `false` to stay retro-compatible. |
> Set dropdown managed to default to false

- vue/components/ui/atoms/dropdown/dropdown.stories.js
- vue/components/ui/atoms/dropdown/dropdown.vue
| - | - |
| --- | --- |
| Decisions | There seem to be no regressions in other Pulse dropdowns (header). |
| Animated GIF | ![image](https://user-images.githubusercontent.com/3048875/86273270-e3071680-bbc7-11ea-897a-67c0f334a220.png) ![image](https://user-images.githubusercontent.com/3048875/86273292-ea2e2480-bbc7-11ea-8b82-2cfdd86e2b9c.png) |
> Add support for dropdown icons

- vue/components/ui/atoms/reaction/reaction.vue
| - | - |
| --- | --- |
| Decisions | Refactor to re-use the `icon` component in `reaction` in order to re-use the "include Ikonate icon" behavior. This was motivated by https://github.com/ripe-tech/ripe-white/pull/507, which adds `reaction` to RIPE White, whereas the icons are in ripe-commons-pluginus, making this change needed in order to: 1. avoid placing `reaction` in ripe-commons-pluginus and 2. avoid duplicating icons in RIPE White and ripe-commons-pluginus. |
> Reuse icon component in reaction

- vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-registry/issues/1 |
| Decisions | Added slot to `select` selected value so it's possible to override what is show to the user after selecting an option |
| Animated GIF | ![select_selected_slot](https://user-images.githubusercontent.com/22588915/91874940-b8dadf00-ec72-11ea-93ac-41a477d9f8fd.gif) |
> Added slot "selected" to "select" component

- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-registry/issues/1 |
| Decisions | Details columns fill all the available space when there isn't any side image. This PR was open because if we use `details-ripe` without an image the columns aren't spaced equally through the container full width. The need for this came when trying to implement `person-show` page https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fdb73a8666bc56f6f70 |
| Animated GIFs | ![details-details_columns_width_improvement](https://user-images.githubusercontent.com/22588915/91537883-e0e2df00-e90e-11ea-8bb4-540aee672108.gif)<br><br>**Needed for `person-show`:** ![person-show_using_details](https://user-images.githubusercontent.com/22588915/91558806-dd5f5000-e92e-11 …
> Details columns in "details-ripe" fill available width

- css/all.scss
- css/variables.scss
- package.json
- vue/test/webpack.config.js
| - | - |
| --- | --- |
| Decisions | Load no CSS when running tests (coherent with https://github.com/ripe-tech/ripe-sdk-components-react/blob/master/react/test/webpack.config.js). This fixes both https://github.com/ripe-tech/ripe-components-vue/pull/358 and https://github.com/ripe-tech/ripe-components-vue/actions/runs/235778755 |
> Fix CSS import

- vue/components/ui/molecules/filter/filter.vue
- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Need to change table in `listing` component. This need first appeared when we wanted to change the field of the table "NAME" https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fda1101d97723f02d1a |
| Decisions | • Can now use `table-ripe` slots from `listing` or `filter` components by using the prefix "table-" followed by the name of the slot <br>• Added prop tableAlignment |
> Support for more table features in filter and listing components

- vue/components/ui/atoms/container/container.vue
- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Decisions | Moved the "floating buttons in bottom" style from `container-ripe` to `details`. |
| Animated GIF | ![image](https://user-images.githubusercontent.com/3048875/92136054-78f73180-ee03-11ea-9345-37dcef8a5e31.png) ![image](https://user-images.githubusercontent.com/3048875/92136192-9fb56800-ee03-11ea-98bf-148b89c98513.png) |
> Buttons in footer only in details

- vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Decisions | Fixes the width of the columns in mobile, skipping the "smart" calculation and always using the default width (50%). |
| Animated GIF | ![](http://g.recordit.co/yrmcBwIubK.gif) |
> Fix details column width in mobile

- vue/components/ui/organisms/listing/listing.stories.js
- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Request to add button-colors to `listing` (ripe-tech/ripe-registry-ui#3) |
| Decisions | Added create button to `listing`. It is enable via the optional prop `createUrl` supports `string` or an `object` which then is used by `router-link` |
| Animated GIF | ![listing_create_button](https://user-images.githubusercontent.com/22588915/92131752-439c1500-edfe-11ea-88ef-c7ad6e566681.gif) |
> Added create button to "listing" component

- vue/components/ui/atoms/breadcrumbs/breadcrumbs.vue
| - | - |
| --- | --- |
| Issue | Avoiding having paths in `breadcrumbs`: https://github.com/ripe-tech/ripe-registry-ui/pull/5#discussion_r482399741 |
| Decisions | Component `breadcrumbs` now uses `router-link` when the property `href` is an `object`.  |
> Support for "router-link" in "breadcrumbs"

- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Decisions | Fix the sorting regression caused by https://github.com/ripe-tech/ripe-components-vue/pull/366 . |
> Fix listing default sort

- vue/components/ui/atoms/input/input.stories.js
- vue/components/ui/atoms/input/input.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-retail-vendors/issues/48 |
| Decisions | Every personalization has a maximum number of characters, and that should be handled by the `input-ripe` component. Backporting from https://github.com/ripe-tech/ripe-white/pull/583 |
> Add maxLength to input-ripe component

- vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Decisions |The need for this came from working on this [issue](https://github.com/ripe-tech/ripe-pulse/issues/146) on Pulse, noticing the disalignment of icon in the button. Keeping the padding when there is a slot because most usages of this component use the slot with just text. |
> Remove padding when text is null

- vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-registry-ui/pull/16 |
| Decisions | Need to use the select slots to be able to customize the select values UI<br>Example of slots in use below, take notice in the two selects that have their entries with an avatar, name and email|
| Animated GIF | <br>![client-create](https://user-images.githubusercontent.com/22588915/92007231-93ff6e00-ed3d-11ea-8b9d-0219f01ddddf.gif) |
> Support select slots in form-ripe

- vue/components/ui/molecules/select/select.vue
- vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-registry/issues/1 |
| Decisions | • Renamed `form-ripe`'s select slots <br>• Support for item in `select` selected slot |
| Animated GIF | ![example](https://user-images.githubusercontent.com/22588915/94424486-361a4680-0182-11eb-973c-ba987c834fbd.gif) |
> Improved select slots

- vue/components/ui/organisms/form/form.stories.js
- vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Issue |https://github.com/ripe-tech/ripe-components-vue/pull/378#issuecomment-701349578 |
| Decisions | • Can use `meta` to specify the input type <br>• To use textarea, instead of just specifying type "textarea" we now do type "text" and  meta "long" <br>• Added new image url input type |
| Screenshot | <img width="1319" alt="imagem" src="https://user-images.githubusercontent.com/22588915/94795317-1a5aae80-03d5-11eb-9663-354acc2481f8.png"> |
> Field types improvements

- vue/components/ui/organisms/entity-lister/entity-lister.stories.js
- vue/components/ui/organisms/entity-lister/entity-lister.vue
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | https://github.com/ripe-tech/ripe-components-vue/pull/386 |
| Decisions | • Created `entity-lister` storybook story <br>• Documented `entity-lister` props <br>• Added prop `listingProps` to `entity-lister` (it was useful to set `listing` `useQuery` prop to `false` in order for the storybook story to work) |
| Animated GIF | ![entity-lister_story](https://user-images.githubusercontent.com/22588915/95472060-7cd62080-097a-11eb-835e-b17a883d24da.gif) |
> Entity lister story and documentation

- vue/components/ui/molecules/input-symbol/input-symbol.stories.js
- vue/components/ui/molecules/input-symbol/input-symbol.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/172 |
| Decisions | Add symbol position property to match input symbol design orientation for WYSIWYG components (https://zpl.io/bzrzn83) |
| Animated GIF | <img width="1146" alt="image" src="https://user-images.githubusercontent.com/24736423/97477944-2be99480-1948-11eb-9bd3-c2045ef21a16.png"> |
> #172 Add symbol position prop to component input-symbol

- css/variables.scss
- vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/172 |
| Decisions | Using secondary icon being when the first is not specified to avoid redundancy in common use cases such as: ` <button-icon-toggle v-bind:icon="'align-left'" v-bind:icon-secondary="'align-left'" />` |
| Animated GIF | ![aaaaaaa](https://user-images.githubusercontent.com/24736423/98700053-add9b480-236f-11eb-83da-88a66af29469.gif) |
> #172 Button-icon: using primary icon when secundary is null

- vue/components/ui/molecules/input-color/input-color.stories.js
- vue/components/ui/molecules/input-color/input-color.vue
| - | - |
| --- | --- |
| Issue | Input color should set color value to be "ffffff" in the native picker when color value is invalid in the user input to match intuitive view. This improves UX for WYSIWYG.  |
| Decisions | Add fix for setting white color when opening native color picker from invalid or null color. Add cleanup to storybook. |
| Animated GIF | ![Peek 2020-11-18 16-36](https://user-images.githubusercontent.com/24736423/99559281-8365a800-29bc-11eb-9f4d-c2abb48cdd7f.gif) |
> Improve input color

- vue/components/ui/molecules/input-symbol/input-symbol.vue
| - | - |
| --- | --- |
| Issue | Need to use icons in input as seen in https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f8852cc4c8b5ca022bb3a9e (https://github.com/ripe-tech/ripe-design/issues/172) |
| Decisions | • Can now use slot `symbol` to replace the symbol in `input-symbol`<br>• Prop `symbol` not set as required anymore |
| Screenshot | ![imagem](https://user-images.githubusercontent.com/22588915/99984075-8c7fbc00-2da4-11eb-915a-ad6c374d7d49.png) |
> #172 Symbol slot for input-symbol

- vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
| - | - |
| --- | --- |
| Issue | https://github.com/NFSS10/peri-wysiwyg/pull/14#discussion_r534277348 |
| Decisions | Class `active` is added when `value `is `true` |
> Add class active when value equals to true

- vue/components/ui/molecules/box-resizable/box-resizable.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/pull/413 |
| Decisions | Fixed unnatural resize interaction when the box has been rotated |
| Animated GIF | **Before:**<br>![problem](https://user-images.githubusercontent.com/22588915/103530035-a968de00-4e7e-11eb-94c2-d2cfb0c9c4f3.gif)<br><br>**After:**<br>![problem_fixed](https://user-images.githubusercontent.com/22588915/103530044-abcb3800-4e7e-11eb-8df2-ffe8436a073c.gif) |
> Improved resize interaction after rotation

- .storybook/preview.js
| - | - |
| --- | --- |
| Issue | Storybook width is not correct so it always has a scrollbar |
| Decisions | Fixed storybook width thus removing the always present scrollbar.<br><br>This issue ocurred because in storybook 6.0 there was an added `padding `of `1rem`. To fix this we needed to add the `fullscreen` param in  `.storybook/preview.js`. (See https://storybook.js.org/docs/vue/configure/story-layout). For more information about this problem, check [this github issue](https://github.com/storybookjs/storybook/issues/12109). |
| Animated GIF | **Before fix:**<br>![storybook_before](https://user-images.githubusercontent.com/22588915/103999777-3d93b780-5195-11eb-8785-5dbbe5bd6ac2.gif)<br><br>**After fix:**<br>![storybook_after](https://user-images.githubusercontent. …
> Fixed storybook not being in fullscreen

- vue/components/ui/atoms/icon/icon.vue
| - | - |
| --- | --- |
| Decisions | Useful to allow extended item-set for client apps. |
> feat: extended icons via $iconSources

- vue/components/ui/atoms/icon/icon.vue
| - | - |
| --- | --- |
| Issue | Small fix iteration through the `iconContexts` to fix error when loading external icon modules e.g. when loading ripe-twitch icons in ripe-twitch-ui. <br /> ![image](https://user-images.githubusercontent.com/24736423/105529703-a83d0b00-5cde-11eb-8090-d2f8d6636c5e.png) |
> Fix context item interation

- vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | Error when selecting a value in a mobile device |
| Decisions | Fixed error when trying to select a value in a mobile device |
| Screenshot | **Error screenshot:**<br>![imagem](https://user-images.githubusercontent.com/22588915/106931121-27363880-670e-11eb-8c3b-35c3be69f035.png) |
> Fix select-ripe value selection error in a mobile device

- vue/components/ui/molecules/index.js
- vue/components/ui/molecules/tooltip/tooltip.stories.js
- vue/components/ui/molecules/tooltip/tooltip.vue
- vue/components/ui/organisms/listing/listing.stories.js
- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-pulse/issues/165|
| Storybook | Tooltip storybook: https://ripe-components-vue-git-ms-165-tooltip-platforme.vercel.app/?path=/story/components-molecules-tooltip--tooltip <br> Listing storybook with tooltip option: https://ripe-components-vue-git-ms-165-tooltip-platforme.vercel.app/?path=/story/components-organisms-listing--listing | 
| Decisions | Tooltip component ported from `white`. Added tooltip to `listing` search (not added in `search` component because it would be very difficult to show the tooltip without being cut out - uses the parent dimensions as reference for positioning). |
| Animated GIF | `Pulse` examples with `listing`: <br>![Screenshot from 2021-03-01 …
> #165: Tooltip in listing's search 

- vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | There is a double arrow problem in `<select-twitch>` which happens when we have a mobile user agent. |
| Decisions | Hide `background-image` when using native select . |
| Animated GIF | The double arrow bug. <br> ![image](https://user-images.githubusercontent.com/24736423/110008246-68bd0200-7d13-11eb-9d20-19353a9f0df5.png) |
> Select: Mobile native toggle

- vue/components/ui/organisms/container-form/container-form.vue
- vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-twitch/issues/84 |
| Decisions | Code necessary to allow override form components with custom ones. <br><br> Its necessary to override the components of a form if a new more specific is needed (for example in the twitch-admin, instead of a switcher, its necessary to use a switcher with a specific behaviour). For that to be possible, a `slot` was added to the `form-input` value and the code necessary to override that slot was added to the container-form, so that its possible to use that slot when using the `entity-create` component. |
| Animated GIF | To allow something like <br> ![image](https://user-images.githubusercontent.com/25725586/110773361-9266b380-8254-11eb-91aa-155cf0e2351e.png)|
> feat: allow form components override

- vue/components/ui/organisms/entity-list/entity-list.vue
| - | - |
| --- | --- |
| Issue | Originated from https://github.com/ripe-tech/ripe-twitch/issues/84 |
| Decisions | Pass item index to `showRoute` method when clicking on a row of the table. <br> To redirect to a page that may contain pagination (`details` component that iterates over the items using the `index` in the query), its necessary to now the index of the item. This just passes that index that is already available to the `onTableRowClick` function. |
> feat: pass item index to show route

- vue/components/ui/organisms/entity-create/entity-create.vue
| - | - |
| --- | --- |
| Issue | Originated from https://github.com/ripe-tech/ripe-twitch/issues/84 |
| Decisions | - Fix `formProps` prop passing of `acceptButtonProps`, which was being overriden. |
> fix: entity create acceptButtonProps

- vue/components/ui/atoms/switcher/switcher.stories.js
- vue/components/ui/atoms/switcher/switcher.vue
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-twitch/issues/42 |
| Decisions | Switcher support for text on checked and unchecked status, and checked color. <br><br> Necessary due to the design in `twitch-admin-ui`, such as the `edit` and `creation`pages: <br>![image](https://user-images.githubusercontent.com/25725586/110812999-04a0bd80-8280-11eb-9f67-968911ec9179.png) <br> ![image](https://user-images.githubusercontent.com/25725586/110813068-12564300-8280-11eb-8e70-9232ec20d4c1.png)|
| Animated GIF |![switcher-text](https://user-images.githubusercontent.com/25725586/110661931-f2118000-81bc-11eb-802e-9a2f9697168c.gif)![switcher-use-case](https://user-images.githubusercontent.com/25725586/110661938-f342ad00-81bc-11eb-84d7-44f2c121f320.g …
> feat: switcher text and color props

- vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Issue | Originated from https://github.com/ripe-tech/ripe-twitch/issues/84 |
| Decisions | The submit action of the form was calling the save callback twice. This was due to the fact that the `onSave` function was being called both on the form submit and on the button click action. https://github.com/ripe-tech/ripe-components-vue/blob/39a41539197931730be306830f94bcc6d88b36d1/vue/components/ui/organisms/form/form.vue#L2 Removed the button action and the call is made correctly only once. |
| Animated GIF |**Problem**: <br> ![form-problem](https://user-images.githubusercontent.com/25725586/110806247-c6a09b00-8279-11eb-8fa8-72ec7804898e.gif) <br> **After fix**:<br>![form-problem-fix](https://user-images.githubusercontent.com/25725586/110806279-d0 …
> fix: remove onSave call from button click

- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-twitch/issues/83|
| Decisions | This slot is necessary for overriding the create entity button in the listing's header. For example, in this screen below, the button needs to have a different text and icon. In addition to this, the button opens a modal instead of redirecting to another page. ![image](https://user-images.githubusercontent.com/25725586/111659922-80ad7f00-8805-11eb-80d9-b839e6c7a1df.png) <br> To allow that kind of behaviour, the easier solution was to create a slot, which changes nothing in the overall behaviour of the component. |
> feat: added slot to listing's header button

- vue/components/ui/molecules/carousel/carousel.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/39 |
| Decisions | - Add infinite slide to the same side of the swipe instead of opposite side when moving from the edges. <br> - Fixes when there are only 2 elements and user clicks several times in the arrow by disabling sliding actions when animating. |
| Animated GIF | ![Peek 2021-03-19 14-59](https://user-images.githubusercontent.com/24736423/111800282-b4e77500-88c3-11eb-93d4-202a9bbbc186.gif) |
> #39 Carousel - infinite slide and double slide fix

- vue/components/ui/molecules/carousel/carousel.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/39 |
| Decisions | - Using vue transiton events to replace native `onanimationend` from `GlobalEventHandlers`. Vue groups all animations into a single event and this way it won't emit several events for the same animation group. |
> #39 Carousel: Using vue transition events instead of native onanimationend

- vue/components/ui/atoms/image-item/image-item.stories.js
- vue/components/ui/atoms/image-item/image-item.vue
- vue/components/ui/molecules/image-list/image-list.stories.js
- vue/components/ui/molecules/image-list/image-list.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/42#issuecomment-806548905 |
| Decisions | Fix highlight color, to make it match the design (the previous color was the color if the hover effect is active, giving it less opacity). Also fixed the default timings, making them match the timings given to the, for example, the notification timeout in entity-show. The original timing was a bit too long. |
| Testing | https://ripe-components-vue-git-ms-fix-image-item-highlight-platforme.vercel.app/?path=/story/components-atoms-image-item--image-item |
| Animated GIF |![fix-highlight-story](https://user-images.githubusercontent.com/25725586/112607562-42215100-8e11-11eb-922d-c1780ec7b6ff.gif)<br>![fix-highlight](https://user-images.githubusercon …
> fix: highlight color and highlight timing

- vue/components/ui/atoms/image-item/image-item.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/84#issuecomment-811251719<br>When the `highlight` prop was true when the component first mounted, the animation did not occur. This occured in `twitch-admin-ui` after going from white to admin-ui, where the first image-item was mounted with the highlight at `true` but the animation did not occur. |
| Decisions | Play the animation when the component is first mounted (if `highlightData` is `true`). Done on mounted because it needs the `$refs.image` to be populated. Extracted animation logic to method. |
> fix: image-item highlight if true when mounted

- package.json
- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/194 |
| Decisions | Like the [design](https://www.figma.com/file/yA0m9ZpxJUeQkOZXjvVtiM/ripe-pulse?node-id=0%3A8030), in mobile mode the search occupies all width and appear above the container title. |
| Problems | The new release [1.1.4 of vue test-utils](https://github.com/vuejs/vue-test-utils/issues/1820) introduced some regressions which caused the `select` to start failing. Issues about the regression: https://github.com/vuejs/vue-test-utils/issues/1820 & https://github.com/vuejs/vue-test-utils/pull/1808 (the PR that possibly caused this regression) | 
| Animated GIF | ![image](https://user-images.githubusercontent.com/25725586/114416713-ded14600-9ba8-11eb-98c7-1dfce9f9ea33.png)|
> fix: search bar uses all width in mobile

- package.json
| - | - |
| --- | --- |
| Issue | CI is failing due to regressions in vue-test-utils 1.1.4 version. A PR is opened but still not addressed: https://github.com/vuejs/vue-test-utils/pull/1826 |
| Decisions | Lock version to 1.1.3 or below. Similar to ripe-white. |
> fix: lock vue-test-utils version

- vue/components/ui/atoms/image-item/image-item.vue
- vue/components/ui/molecules/image-list/image-list.vue
| - | - |
| --- | --- |
| Issue | Image becomes undesirably stretched in case the image source isn't 1:1 width:height ratio.  |
| Decisions | Using [object-fit contain](https://developer.mozilla.org/pt-BR/docs/Web/CSS/object-fit#syntax). |
> Image Item: fix image fit

- CHANGELOG.md
- vue/components/ui/molecules/select-checkboxes/select-checkboxes.stories.js
- vue/components/ui/molecules/select-checkboxes/select-checkboxes.vue
| - | - |
| --- | --- |
| Issue | Motivated several ad-hoc implementations (e.g. ripe-tech/ripe-util-vue#53) that did the same over and over. |
| Dependencies | https://github.com/ripe-tech/ripe-components-vue/pull/484 |
| Animated GIF | ![](http://g.recordit.co/z8LrZWXDVc.gif) |
> feat: better default labels for select-checkboxes

- CHANGELOG.md
- vue/components/ui/atoms/image-item/image-item.vue
- vue/components/ui/molecules/image-list/image-list.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/60 |
| Decisions | Add slot to allow the override of `name` field. In the context of the issue it will allow the addiction of the review buttons. |
| Animated GIF | ![image](https://user-images.githubusercontent.com/24736423/116890814-ef179680-ac25-11eb-82c0-b49cf32e2f44.png) |
> #60 Add image list and imagem item slots

- CHANGELOG.md
- vue/components/ui/molecules/image-list/image-list.vue
| - | - |
| --- | --- |
| Decisions | Optionally using `item.id` as key. This fixes the problem when the items change but the index is the same. We're also using this pattern in other components e.g. `<table>`. |
> Image list: Option to use id as a key

- CHANGELOG.md
- vue/components/ui/atoms/radio/radio.vue
- vue/components/ui/molecules/radio-group/radio-group.vue
- vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | There's a restriction for the prop value to be `String` only type in some components. This might be a hassle for some data sources that could be defined to using native number values .e.g a select with values `[{ label: "One", value: 1 }]` and having to add extra logic to cast and uncast in computed variables when the component could simply accept and emit the native value as is. Note that we're [already doing this](https://github.com/ripe-tech/ripe-components-vue/blob/master/vue/components/ui/atoms/input/input.vue#L97) in `<input>` |
| Decisions | - Extend https://github.com/ripe-tech/ripe-components-vue/pull/136 fix to other components. This also fixes some warn messages for some implementations when the number isn't casted to `String`. |
> Accepting numbers in value prop

- CHANGELOG.md
- vue/components/ui/atoms/container/container.stories.js
- vue/components/ui/atoms/container/container.vue
| - | - |
| --- | --- |
| Decisions | Before this change only button icons were supported. While they remain the default, it should be possible to use other types of buttons.  |
| Animated GIF | ![image](https://user-images.githubusercontent.com/3048875/119681500-08cd8780-be3a-11eb-842d-1f69a42333f9.png) |
> feat: container header buttons type

- CHANGELOG.md
- vue/components/ui/atoms/radio/radio.vue
- vue/components/ui/molecules/radio-group/radio-group.vue
- vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | Currently it's not possible to pass an object as a value in `<select>` prop `options` and components that involves selecting a value from an array of options. |
| Decisions | - Remove type limitation for `<select>` <br> - Back porting might be necessary after acceptance |
> Add typeless value support

- CHANGELOG.md
- vue/components/ui/molecules/upload-area/upload-area.vue
| - | - |
| --- | --- |
| Decisions | This was originated by a behaviour found in [rules uploader utility](https://github.com/ripe-tech/ripe-util/issues/72) that prevented normal functionality. If for some reason the parent component discard the selected file [sent by upload-area](https://github.com/ripe-tech/ripe-components-vue/blob/f25c04a26a9266d387c7fca9f695f0bfdc3879bf/vue/components/ui/molecules/upload-area/upload-area.vue#L173) and would want to grab the file again, on file selection, the upload-area component would still have the file selected, the event would not get triggered. because the component would not seet it as a change So, with other approaches less "cirurgical", I decided to clear the input on buttonclick |
| Animated GIF | With fix …
> fix: fix upload area component

- vue/components/ui/molecules/modal/modal.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/69#issuecomment-861521404 |
| Decisions | - Fix title overlapping close button space by decreasing total space by 18 pixels (space occupied by close button element including padding) |
| Animated GIF | <img width="512" alt="image" src="https://user-images.githubusercontent.com/24736423/122066493-b0f7c000-cdea-11eb-95ff-db8142af397e.png"> |
> Modal: fix title width

- vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Issue | `v-bind:value=...` should be `v-bind:values=...` |
| Decisions | Resolve typo in `v-bind:values` of `input-list` in `form-ripe` |
> Resolved input-list bad v-bind

- package.json
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/165 |
| Decisions |  Bump commons dependency. After this is merged, `components-vue` needs a release so that I can bump it on rie-pulse. |
> feat: bump commons dependency

- vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Decisions | - Using long hand watch methods to allow the use of `immediate` <br> - Setting first options value when receiving single option array: <br> ` if (value?.length === 1) this.valueData = value[0].value;` |
> Select: single option selects first value

- CHANGELOG.md
- vue/components/ui/molecules/alert/alert.vue
| - | - |
| --- | --- |
| Description | Issue detected in while doing https://github.com/ripe-tech/ripe-util/issues/72 |
| Screenshots | Before <br> <img width="802" alt="modal-not" src="https://user-images.githubusercontent.com/8842023/126138900-3f940265-0782-4fef-afbb-125f21b8f890.png"> After <br> <img width="854" alt="modal-yes" src="https://user-images.githubusercontent.com/8842023/126138987-f86997aa-832f-4a78-a381-a587ce26695c.png">|
> fix: word break in alert text

- CHANGELOG.md
- vue/components/ui/molecules/image-list/image-list.vue
| - | - |
| --- | --- |
| Issue | Making the selected images more evident, as mentioned in https://github.com/ripe-tech/ripe-util-vue/issues/60#issuecomment-874229687 |
| Decisions | Allowed the opacity of the unselected images to be lowered by props. |
| Animated GIF | ![](http://g.recordit.co/B3ew9Aih7B.gif) |
> #60 Visual Testing  -  image list more evident selected image

- vue/components/ui/molecules/select-checkboxes/select-checkboxes.vue
- vue/components/ui/molecules/select/select.vue
- vue/mixins/scroll.js
- vue/mixins/utils.js
| -| - | 
| ---| --- | 
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/125 |
| Dependencies | None |
| Decisions | Select checkboxes didn't have the feature to scroll to the closest match when input is given, so this PR adds that feature.  |
| Animated GIF | ![Peek 2021-07-22 09-31](https://user-images.githubusercontent.com/22790704/126611062-11ea88f1-35d1-49ef-a631-8aa84f715cce.gif) |
> #125 Select checkboxes can scroll to match when using input

- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/234 |
| Decisions | - Add key only option to allow adding filters like addFilter("@today") resulting in `@today` instead of `@today=undefined` |
> Listing: add key only option to addFilter

- CHANGELOG.md
- vue/components/ui/molecules/button-upload/button-upload.stories.js
- vue/components/ui/molecules/button-upload/button-upload.vue
- vue/mixins/upload.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/pull/532#issuecomment-916710005 |
| Decisions | - Fix `buttonText` label when multiple is `true` <br> - Fix multiple files being set when dragging even when multiple was set to `false` |
| Animated GIF | ![Peek 2021-09-10 11-18](https://user-images.githubusercontent.com/24736423/132839170-57b698b9-e8dd-42bb-9d87-184cbededcd6.gif) |
> Button Upload: label and multiple fix

- CHANGELOG.md
- vue/components/ui/atoms/index.js
- vue/components/ui/atoms/svg-viewer/svg-viewer.js
- vue/components/ui/atoms/svg-viewer/svg-viewer.stories.js
- vue/components/ui/atoms/svg-viewer/svg-viewer.vue
- vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/921 |
| Decisions | • Create `svg-viewer` component which let's us preview an SVG or SVGA given the file URL<br>• Support for SVG url field for `form-ripe` component, given that the field meta is `svg-url` |
https://user-images.githubusercontent.com/22588915/140169854-106c11bd-c523-4856-a05d-cfbc54379939.mp4
> #921 SVG viewer and `svg-viewer` in `form`

- vue/components/ui/atoms/image-item/image-item.vue
- vue/components/ui/molecules/image-list/image-list.vue
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-util-vue/issues/214#issuecomment-954504759 |
| Decisions | - Support for selected style (show border in selected item in the list)<br>- Fix overflow cut in the left side of the image list (GIF below)<br>![image-ist-left-overflow](https://user-images.githubusercontent.com/25725586/139424262-741883e3-a03c-4035-b200-efc8ab8aff8b.gif)|
| Animated GIF | Selected style:<br>![order-validation-image-list-selected](https://user-images.githubusercontent.com/25725586/139424295-e96f812d-a556-49c9-8a16-92138f5613fe.gif)<br>Fix overflow cut:<br>![image-ist-left-overflow-fix](https://user-images.githubusercontent.com/25725586/139424331-87c12d8c-0083-47d5-bd23-2d6545a9e6ed.gif)|
> feat: image item list selected style

- CHANGELOG.md
- package.json
* Created `svg-viewer` component - [#921](https://github.com/ripe-tech/ripe-white/issues/921)
* Support for SVG url field in `form-ripe` component, given that the field meta is `svg-url` - [#921](https://github.com/ripe-tech/ripe-white/issues/921)
* Support for selected style (show border in selected item in the list) in `image-item` and `image-list`
* Overflow cut in the left side of the `image-list` component
> version: 0.17.0

- vue/components/ui/molecules/filter/filter.vue
| - | - |
| --- | --- |
| Issue | Using this in https://github.com/ripe-tech/ripe-util-vue/pull/229, where its necessary to update a table item after some update on it. The `$set` was being used incorrectly. |
| Decisions | - The `$set` was being used incorrectly, fixed that. |
> fix: filter setItem $set usage

- vue/components/ui/molecules/filter/filter.vue
- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Currently the rows of the `<listing>` component are styled with `cursor: pointer` but actually not all that area is clickable in most cases.  |
| Decisions | - Add missing `clickableRows` prop so we're able to control table's prop from filter or listing component. <br> - Add missing `::v-deep .clickable` selector styling for specific items we want as clickable in listing |
> Listing: clickable rows

- CHANGELOG.md
- vue/components/ui/molecules/input-image/input-image.stories.js
- vue/components/ui/molecules/input-image/input-image.vue
| - | - |
| --- | --- |
| Decisions | - Fix shrink making remove button invisible (check GIF below). <br> - Add variant background color prop. |
Note: This component will later be used for the order creation form in ripe-util-vue.
> Input Image: small improvements

- CHANGELOG.md
- vue/components/ui/atoms/tag/tag.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/296 |
| Decisions | Add `textColor` prop to `tag` component |
| Screenshot | ![imagem](https://user-images.githubusercontent.com/22588915/152849760-774177d0-c7c7-4809-974e-0df459c10fca.png) |
> #296 Add `textColor` prop to `tag` component

- CHANGELOG.md
- vue/components/ui/molecules/progress-bar/progress-bar.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/296 |
| Decisions | Add `backgroundColor` prop to `progress-bar` component |
| Screenshot | ![imagem](https://user-images.githubusercontent.com/22588915/152852880-623e5f66-bcc8-42b4-ba4a-8fbadc7198f1.png) |
> #296 Add `backgroundColor` prop to `progress-bar` component

- CHANGELOG.md
- vue/components/ui/atoms/dropdown/dropdown.stories.js
- webpack.config.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/pull/965#discussion_r805148458 |
| Decisions | - Removed `href` from `dropdown` stories that caused the site to open inside the storybook and break navigation |
> fix: removed href from dropdown story

- CHANGELOG.md
- vue/components/ui/atoms/image-item/image-item.vue
| - | - |
| --- | --- |
| Issue | The image did not have border radius applied:<br>![image](https://user-images.githubusercontent.com/25725586/154309315-5f7403d8-c996-461d-9b18-69a19ebc86b9.png)<br>Can be seen in `ripe-util-vue`'s storybook:<br>![image](https://user-images.githubusercontent.com/25725586/154309486-edff9e62-45e7-4b08-b2b8-bfc036616834.png) |
| Decisions | - Add `overflow: hidden` and `box-sizing: border-box` to `image-item` styling and reduce the image size by `1px` so that the border can be seen |
| Animated GIF | Now:<br>![image](https://user-images.githubusercontent.com/25725586/154309196-b90793db-113c-4060-909b-5f2f5f730c17.png)<br>![image](https://user-images.githubusercontent.com/25725586/154309603-b365eab7-39dd-4827-a50d-de9a5fcffece.png)|
> fix: apply correctly the border radius in `image-item`

- CHANGELOG.md
- vue/components/ui/molecules/index.js
- vue/components/ui/molecules/section-expandable/assets/arrow-down.svg
- vue/components/ui/molecules/section-expandable/index.js
- vue/components/ui/molecules/section-expandable/section-expandable.stories.js
- vue/components/ui/molecules/section-expandable/section-expandable.vue
| - | - |
| --- | --- |
| Issue | Requested in the issue https://github.com/ripe-tech/ripe-util-vue/issues/247 |
| Decisions | There was a need to a section that could be collapsed or expanded at will. This PR adds a new `section-expandable-ripe` component, that is similar to the basic `section` component, with the extra logic for the collapse of information. |
| Screenshots | ![Screen Recording 2022-02-28 at 17 17 16](https://user-images.githubusercontent.com/22790704/156029306-03f57ffb-54ef-4c4f-96d8-3b31d5db399a.gif) Don't know why it's in slow-motion, but it's in regular speed when using! |
> Added Expandable Section

- CHANGELOG.md
- vue/components/ui/molecules/table-expandable/table-expandable.vue
- vue/components/ui/molecules/table/table.vue
- vue/components/ui/organisms/table-menu/table-menu.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-core/issues/4659 |
| Decisions | If the sorting value is equal for both, we should give priority to the first element. For example, pulse states with same timestamp (due to simultaneous multiple transitions). |
| Animated GIF | ![Peek 2022-02-28 12-36](https://user-images.githubusercontent.com/16060539/155984895-3f9e8a4e-d6c6-4f75-a89c-e7cd622572c2.gif) |
> fix: table sort

- CHANGELOG.md
- vue/components/ui/molecules/section-expandable/section-expandable.stories.js
- vue/components/ui/molecules/section-expandable/section-expandable.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/265 |
| Decisions | Support `expanded` prop in `section-expandable` component |
https://user-images.githubusercontent.com/22588915/160598713-1beadc5a-4af6-4def-b654-349646b3cbf7.mov
> #256 Support `section-expandable` new `expanded` prop

- CHANGELOG.md
- vue/components/ui/molecules/section-expandable/section-expandable.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/265 |
| Decisions | Fix `section-expandable` not handling dynamic content height changes |
https://user-images.githubusercontent.com/22588915/161044423-f0643e30-8477-4797-8401-53907d7a4585.mp4
> #265 Fix `section-expandable` not handling dynamic content height

- CHANGELOG.md
- vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.stories.js
- vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281 |
| Decisions | Disable the button icon dropdown prop. |
| Animated GIF | ![button icon dropdown disable](https://user-images.githubusercontent.com/16060539/161103897-ab70e5f5-6846-4847-a99d-226ebcb5da60.gif) |
> feat: disabled button icon dropdown

- CHANGELOG.md
- vue/components/ui/atoms/dropdown/dropdown.vue
- vue/components/ui/organisms/header/header.stories.js
- vue/components/ui/organisms/header/header.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/316 |
| Decisions | • Add proper `dropdown` click event that supports `event` parameter (maitaining backwards compatibility)<br>• Support customization of the account dropdown list in the `header-ripe` component<br>• Support custom panel in the `header-ripe` component |
https://user-images.githubusercontent.com/22588915/161925503-89e5c0ef-e201-4fd2-abd3-e3a482741cb1.mov
https://user-images.githubusercontent.com/22588915/161925494-f08e3e51-4966-45d1-ba90-d23f1a4edd63.mov
> #316 Support custom panel in `header-ripe`

- CHANGELOG.md
- vue/components/ui/organisms/header/header.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/316 (related: to https://github.com/ripe-tech/ripe-components-vue/pull/573) |
| Decisions | Revert refactor breaking changes. `extraPanelScopedSlots` is not a string, it's an array already filtering the slots for the panel |
> #316 Fix `header-ripe` by reverting some refactor changes

- CHANGELOG.md
- vue/mixins/upload.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/issues/580 |
| Decisions | If `FileList` is empty do not set internal value |
| Animated GIF | ![UmMGJ3YGAg](https://user-images.githubusercontent.com/8842023/163137218-e951fee7-2b18-4988-b528-77f62662edf3.gif) |
> #580 Closing the file browser dialog removes the previous selected file in upload components #580

- CHANGELOG.md
- vue/components/ui/atoms/icon/icon.vue
| - | - |
| --- | --- |
| Issue | Problem found by @NFSS10: In util-vue, the icons provided by that repo but accessible by `require.context` were not being shown <br>![image](https://user-images.githubusercontent.com/25725586/164275965-476c9461-3dd1-4841-8076-5e576c6bb3d5.png)<br>(related https://github.com/ripe-tech/ripe-util-vue/issues/270) |
| Decisions | - In icon loading, support both the logic of webpack5 (the `raw` query param that allow using the `asset/source` loader from webpack@5) and the previous logic (without `raw` and uses `raw-loader`, that requires the decomposition of the returned object with `.default`). **This is a problem because `ripe-util-vue` uses webpack 4 because Nuxt@2 does not support webpack 5** |
| Animated GIF | …
> #270 Support webpack@4 `raw-loader` logic for icons provided by external sources 

- CHANGELOG.md
- vue/components/ui/atoms/button-color/button-color.stories.js
- vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/270 |
| Decisions | Add prop `iconPosition` to `button-color` allowing to change the icon position |
https://user-images.githubusercontent.com/22588915/164482715-e33019be-ec82-449a-82c0-c6a6e74203d8.mp4
> #270 `iconPosition` prop for `button-color`

- CHANGELOG.md
- vue/components/ui/atoms/input/input.stories.js
- vue/components/ui/atoms/input/input.vue
| - | - |
| --- | --- |
| Issue | Suggestion by @joamag  |
| Decisions | - Added prop `debounceTime` to component `input-ripe` allowing a delay between the input events and the actual `setValue`  |
https://user-images.githubusercontent.com/24736423/166245651-2510d534-9107-4063-9ca0-23df0ebff3a9.mov
> Input: `debounceTime` prop

- CHANGELOG.md
- vue/components/ui/atoms/dropdown/dropdown.vue
- vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281 https://github.com/ripe-tech/ripe-pulse/issues/281#issuecomment-1084775305 |
| Decisions | Emit proper events for open/closing of the dropdown and have open/close methods for abstraction purposes. |
| Animated GIF | ![281-open-close-dropdown](https://user-images.githubusercontent.com/16060539/166692378-ef1ce405-1f45-4b39-94d2-288d684e285e.gif) |
> feat: global hide prop in button icon dropdown

- .github/workflows/main.yml
- CHANGELOG.md
| - | - |
| --- | --- |
| Issue | Node `16` is LTS and currently CI/CD isn't running for that version. `ripe-components-vue` is a very active project, thus this project should have an active maintenance (relevant: https://github.com/ripe-tech/ripe-welcome/pull/187#issue-1241883511) |
| Decisions | Added node `16`, `17` and `18` to github CI/CD |
Reference: https://nodejs.org/en/about/releases/
**NOTE:** Github jobs are failling because of the known storybook issue https://github.com/ripe-tech/ripe-welcome/pull/187#issue-1241883511
> Support node `16` , `17` and `18`

- CHANGELOG.md
- vue/components/ui/molecules/code-editor/code-editor.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/305 |
| Decisions | The `$emit` event should be `update:value` instead of `value` |
> #305 Fix `code-editor` `value` emit event

- CHANGELOG.md
- vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Issue | Issue came up while reviewing https://github.com/ripe-tech/ripe-util-vue/issues/288 to access the sorted items |
| Decisions |Emit an event whenever the `sortedItems` are updated  |
> #288 sortedItems Event

- CHANGELOG.md
- vue/components/ui/molecules/button-dropdown/button-dropdown.stories.js
- vue/components/ui/molecules/button-dropdown/button-dropdown.vue
| - | - |
| --- | --- |
| Issue | Issue surged with https://github.com/ripe-tech/ripe-util-vue/issues/288 where the `button-dropdown` needed to be disabled|
| Decisions | Add `disabled` prop to `button-dropdown`|
| Animated GIF |![](http://g.recordit.co/EpjzUNYBrL.gif)|
> #288 button-dropdown disabled prop

- CHANGELOG.md
- package.json
* Add `input-file` component - [ripe-copper/#48](https://github.com/ripe-tech/ripe-copper/issues/48)
* Add slots to `input-symbol` component - [ripe-util-vue/#259](https://github.com/ripe-tech/ripe-util-vue/issues/259)
* Button icon dropdown global hide prop - [ripe-pulse/#281](https://github.com/ripe-tech/ripe-pulse/issues/281)
* Add `avatar-list` component - [#571](https://github.com/ripe-tech/ripe-components-vue/issues/571)
* Added prop `debounceDelay` to component `input-symbol` - [#259](https://github.com/ripe-tech/ripe-util-vue/issues/259)
* Add node `16`, `17` and `18` support
* Fix spreadsheet icon's stroke width
> version: 0.23.1

- CHANGELOG.md
- vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Issue | [ripe-util-vue/#307](https://github.com/ripe-tech/ripe-util-vue/issues/307) |
| Decisions | Add a footer slot so the `pagination` component can be placed |
> feat: add `table-footer` slot to `table` component

- CHANGELOG.md
- vue/components/ui/atoms/icon/icon.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/348 <br> `iconContexts` allow us to have a list of custom icons besides the default ikonate icons. We're using it in [some projects](https://github.com/search?q=org%3Aripe-tech+iconContexts&type=code) (all webpack 4). Currently there are no webpack5 projects implementing this and it looks like the implementation has always been broken. We never noticed until now that ripe-pulse (webpack 5) needs to implement this.   |
| Decisions | - Fix webpack 5 `iconContexts` sufix path. |
> fix: proper icon context paths

- CHANGELOG.md
- package.json
* Added `iconProps`, `uppercase` and `size` to `section-expandable`'s props - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
* Add `pagination` component - [ripe-util-vue/#307](https://github.com/ripe-tech/ripe-util-vue/issues/307)
* Add `primaryColor` and `secondaryColor` prop to `dropdown-button` - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
* Add better loading style for other colors - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
* Remove hover and interaction while loading - [ripe-util-vue/#288](https://github.com/ripe-tech/ripe-util-vue/issues/288)
* Add `table-footer` slot to `table` component - [ripe-util-vue/#307](https://github.com/ripe-tech/ripe-util-vue/issues/307)
* Fix Icon contexts …
> version: 0.23.2 :rainbow: 

- CHANGELOG.md
- vue/components/ui/molecules/button-upload/button-upload.vue
- vue/mixins/upload.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/issues/612 |
| Decisions | -Move common logic to the `upload` mixin |
| Animated GIF | ![T0yp5QhkP8](https://user-images.githubusercontent.com/8842023/198069412-7231c2ab-3076-4992-8d4a-6bcfc3b5d04b.gif) |
> #612 `upload-area` component not clearing data

- CHANGELOG.md
- vue/components/ui/molecules/input-file/input-file.vue
- vue/components/ui/molecules/upload-area/upload-area.vue
- vue/mixins/upload.js
| - | - |
| --- | --- |
| Issue | - |
| Dependencies | - |
| Decisions |Conceptually, `computed` values in `vue` are used when logic needs to be triggered when component internal `state` changes weather the logic is conditional to the state itself. In this specific case, `emptySlots()` is running only one time on component creation, limiting use-cases when the parent component adds or removes slots accordingly (see screenshots below) not removing the button when a slot is added. What was done to fix this:  <br> <br> - Reference the respective data property to react to, and use it in a way that doesn't alter the returning boolean expression  |
| Animated GIF | No slots: <img width="718" alt="Screenshot 2022-10-27 at 15 56 46" src="https://user-images.githubusercontent.com/8842023/198324835- …
> feat: add reacticity to `emptySlots()` computed property in `molecules/upload-area.vue`

- CHANGELOG.md
- package.json
| - | - |
| --- | --- |
| Issue | - `@vue/test-utils` is throwing when building to run tests because of a breaking change after `1.3.0` version.  |
| Decisions | - Fix test-utils version to `1.3.0`  |
> fix: fix test-utils version to 1.3.0

- CHANGELOG.md
- vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/240 |
| Decisions |The `addFilter` method wasn't dealing well with a previously `null` filter. Made some changes so it can function properly in all foreseen cases.|
> #240 Filter orders - fix add filter

- .github/workflows/deploy.yml
- .github/workflows/main.yml
- CHANGELOG.md
| - | - |
| --- | --- |
| Issue | odd versions shouldn't be supported + node 12 should be deprecated as even node 14 will stop being supported at the end of this month |
| Decisions | * Only support Node.js LTS versions (`14`, `16`, `18`) <br>* Update `deploy.yml` Node.js version to `18` |
> Only support Node.js LTS versions (14, 16, 18)
