package.json, vue/components/ui/header-platforme/header-platforme.vue
Even though we won't be using it just yet, it might be helpful in the future.
=> Add class for easier selection when testing

vue/components/ui/filter-platforme/filter-platforme.vue
https://recordit.co/UZKRpP7kGr
=> RS-242: Fixed filter bug when fast typing

vue/components/ui/table-platforme/table-platforme.stories.js, vue/components/ui/table-platforme/table-platforme.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Add storybook to table component. Also centers table row's content.  |
| Animated GIF | <img width="1316" alt="imagem" src="https://user-images.githubusercontent.com/24736423/68938209-c97aa100-0795-11ea-8926-6898d99defa5.png">  |
=> Add storybook to table component

vue/components/index.js, vue/components/ui/alert-platforme/alert-platforme.vue, vue/components/ui/modal-platforme/modal-platforme.vue, vue/mixins/part.js
| - | - |
| --- | --- |
| Issue |  |
| Decisions |  |
| Animated GIF | https://recordit.co/Of4pXAhRoM  |
Usage:
```javascript
await this.doAlert(
{
title: "Confirm cancel",
text: "Are you sure you want to cancel this order?"
},
async () => {
await this.$ripeApi.cancelOrderP(this.id);
await this.refresh();
}
)
```
=> Added PlatformeAlert

vue/components/ui/dropdown-platforme/dropdown-platforme.stories.js, vue/components/ui/filter-platforme/filter-platforme.vue, vue/components/ui/header-platforme/header-platforme.vue
https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax
=> Remove deprecated slot-scope

vue/components/index.js, vue/components/parts/global-platforme/global-platforme.vue, vue/components/ui/listing-platforme/listing-platforme.vue, vue/mixins/device.js, vue/mixins/index.js
=> Device change mixin

vue/components/ui/button-icon-platforme/button-icon-platforme.vue
=> Add button icon height

vue/components/ui/tag-platforme/tag-platforme.vue
Avoids unwanted height inheritance.
=> Add default height to label

vue/components/index.js, vue/components/ui/tabs-platforme/tabs-platforme.vue, vue/components/ui/textarea-platforme/textarea-patforme.stories.js, vue/components/ui/textarea-platforme/textarea-platforme.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Created textarea component.  |
| Animated GIF | ![textarea](https://user-images.githubusercontent.com/22588915/69948053-d5c96280-14e6-11ea-8c0d-141f19ebff3c.gif) |
=> Textarea component

vue/components/ui/header-platforme/header-platforme.vue, vue/components/ui/overlay-platforme/overlay-platforme.vue, vue/components/ui/side-platforme/side-platforme.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions |  - |
=> Fix layer level of components

vue/components/ui/modal-platforme/modal-platforme.vue
=> Re-center modal on DOM changes

vue/components/ui/modal-platforme/modal-platforme.vue, vue/components/ui/tabs-platforme/tabs-platforme.vue
| - | - |
| --- | --- |
| Issue | - |
=> Fix tabs resize height

vue/components/ui/details-platforme/details-platforme.stories.js
| - | - |
| --- | --- |
| Issue | Small error on the props name, leading to wrong docs |
| Decisions | Correct the name  |
=> Fix small typo on the props name

vue/components/ui/molecules/tabs/tabs.vue
| - | - |
| --- | --- |
| Issue | Component has a internal padding that should be decided by the dynamic component that will fill that area  |
| Decisions | Remove the internal padding    |
=> Fix tabs component padding

vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | Needed more control on the header title and the centered container |
| Decisions |  Add new slots for possible customisation  |
=> Added new header title and center cotainer slots

vue/components/ui/footer-platforme/footer-platforme.stories.js
| - | - |
| --- | --- |
| Issue | - |
=> Remove unused old file

vue/components/ui/molecules/search/search.vue, vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | - |
=> Fix search field width of listing component

vue/components/ui/atoms/side/side.stories.js, vue/components/ui/atoms/side/side.vue, vue/components/ui/organisms/header/header.stories.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Changed side component id and text attributes to label and value, to be in agreement with other components (checkbox, radio, dropdown, ...). Also added story for side component. |
=> Side Component Story and id+text into value+label

css/colors.scss, vue/components/ui/atoms/button-color/button-color.vue, vue/components/ui/atoms/dropdown/dropdown.vue, vue/components/ui/atoms/input/input.vue, vue/components/ui/atoms/textarea/textarea.vue, vue/components/ui/molecules/index.js, vue/components/ui/molecules/modal/modal.vue, vue/components/ui/molecules/select/assets/chevron-down.svg, vue/components/ui/molecules/select/select.stories.js, vue/components/ui/molecules/select/select.vue, vue/components/ui/organisms/header/header.vue
=> Select component

vue/components/ui/atoms/bubble/bubble.stories.js
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Bubble component story |
=> Bubble component story 

vue/components/ui/atoms/rich-textarea/rich-textarea.vue
=> Add width prop to rich-textarea

vue/components/ui/organisms/details/details.stories.js, vue/components/ui/organisms/details/details.vue
=> Fixed details slots example

vue/components/ui/molecules/select/select.vue
=> Select text no longer on top of arrow

vue/components/ui/atoms/rich-textarea/rich-textarea.stories.js, vue/components/ui/atoms/rich-textarea/rich-textarea.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | User can now select attachments to upload.  |
| Animated GIF | ![rich-textarea-attachments](https://user-images.githubusercontent.com/22588915/71473275-3e49ed80-27ce-11ea-8ea8-1640325e0924.gif) |
=> Rich Textarea - Attachments behaviour 

vue/components/ui/molecules/select/select.vue
=> Add slots to select

vue/components/ui/molecules/index.js, vue/components/ui/molecules/upload-area/upload-area.stories.js, vue/components/ui/molecules/upload-area/upload-area.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Allows the user to upload files by selecting the files or by dragging and dropping them. It can also turn a custom element in a drag and drop area, when that element is passed to the slot. |
| Animated GIF | **Default drag and drop:** ![drag_n_drop_default](https://user-images.githubusercontent.com/22588915/71626877-40091c00-2be7-11ea-8e48-7c144d77874b.gif) **Using the button:** ![drag_n_drop_default_button](https://user-images.githubusercontent.com/22588915/71626878-41d2df80-2be7-11ea-82ff-888e71946532.gif) **Using a custom element as the drag and drop area:** ![drag_n_drop_custom](https://user-images.githubusercontent.com/22588915/71626879-426b7600-2be7-11ea-96bb-232c9d56b7c8.gif) |
=> Upload area component

vue/components/ui/molecules/upload-area/upload-area.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | "description" and "descriptionDragging" props had their types as Arrays, but they should be String.  |
=> Fixed upload-area component "description" and "descriptionDragging" props

vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue |In Mobile view the value wasn't being updated when selected and the UI wasn't as expected|
| Decisions | Fix the value update when selected, changed to the new UI and added some rules to the component |
| Before the fix  | <img width="1393" alt="Screenshot 2020-01-06 at 11 51 53 2" src="https://user-images.githubusercontent.com/13239857/71830239-404d5f80-309e-11ea-8260-2738862c7827.png">|
| After the fix |<img width="394" alt="Screenshot 2020-01-06 at 15 35 45" src="https://user-images.githubusercontent.com/13239857/71830189-20b63700-309e-11ea-8c6f-d13e59035642.png">|
=> Fix mobile view of selector component

vue/components/ui/atoms/rich-textarea/rich-textarea.vue
=> Attachments scrollbar not on top of content anymore

vue/components/ui/atoms/button-color/button-color.stories.js, vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Added min-width prop to button-color, applied it into style. |
=> Button Color min-width Prop

vue/components/ui/molecules/tabs/tabs.stories.js, vue/components/ui/molecules/tabs/tabs.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Added prop that receives the alignment of the tabs header |
=> Tabs header alignment prop

vue/components/ui/templates/error-part/error-part.stories.js, vue/components/ui/templates/error-part/error-part.vue, vue/components/ui/templates/oauth-part/oauth-part.stories.js
| - | - |
| --- | --- |
| Issue | The error screen didn't had a button to go back or to go to the home screen |
| Decisions | Added a back button and added to the existing logo image the click event to go to home page  |
=> Error component improvement 

vue/components/ui/atoms/button-icon/button-icon.stories.js, vue/components/ui/atoms/button-icon/button-icon.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions |  Adds a black color to the button icon. |
| Animated GIF | ![button-icon_inverted_color](https://user-images.githubusercontent.com/22588915/71909790-9d154c80-3168-11ea-994c-9d53039aa22f.gif) |
=> Button icon black color

vue/components/ui/organisms/details/details.vue
| - | - |
| --- | --- |
| Issue | There was a need to create an option for adding more buttons in the detail header. |
| Decisions |  Added new slot to the detail header buttons, so we can add in the same div has in the already existing buttons |
=> Added new slot to the detail header buttons

vue/components/ui/molecules/filter/filter.vue, vue/components/ui/molecules/lineup/lineup.stories.js, vue/components/ui/molecules/lineup/lineup.vue, vue/components/ui/organisms/details/details.stories.js, vue/components/ui/organisms/details/details.vue, vue/components/ui/organisms/listing/listing.vue, vue/mixins/filter.js
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Improved lineup style and also added prop "nrColumns" that allows to define how many columns should the lineup component have. |
| Animated GIF | **Nr Columns:**<br>![lineup_nrColumns](https://user-images.githubusercontent.com/22588915/72340682-828b2800-36c0-11ea-846f-72477ec43b12.gif)**Responsive:**<br>![lineup_responsive](https://user-images.githubusercontent.com/22588915/72340683-828b2800-36c0-11ea-8137-21f305a9b874.gif) |
=> "lineup" component style

vue/components/ui/atoms/checkbox/checkbox.vue, vue/components/ui/atoms/dropdown/dropdown.vue, vue/components/ui/molecules/search-persistent/save-filter-modal.vue, vue/components/ui/molecules/search-persistent/search-persistent.stories.js, vue/components/ui/molecules/search-persistent/search-persistent.vue, vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | Related to issue https://github.com/ripe-tech/ripe-components-vue/issues/166 |
| Decisions |  • Depends on the addition of slots in "checkbox" component implemented in PR: https://github.com/ripe-tech/ripe-components-vue/pull/192 <br>• Made the improvements specified in the following comments: [Comment 1](https://github.com/ripe-tech/ripe-components-vue/pull/166#issuecomment-575211514), [Comment 2](https://github.com/ripe-tech/ripe-components-vue/pull/166#issuecomment-575545847) |
| Animated GIF | ![persitent-filters_imp2](https://user-images.githubusercontent.com/22588915/72792599-36486680-3c31-11ea-97b3-51d0f9bec2da.gif) <br>**Creating a filter that already exists, updates the existing one:** ![persistent-filters_imp3](https://user-images.githubuserconte …
=> Persitent Filters - Tenancy improvements

css/colors.scss, vue/components/ui/atoms/button-icon/button-icon.vue, vue/components/ui/molecules/tabs/tabs.vue
=> Small changes

vue/components/ui/atoms/checkbox/checkbox.stories.js, vue/components/ui/atoms/checkbox/checkbox.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions |  Added slots to the "checkbox" component. |
| Animated GIF | **Example of a select that was added to the slot, that appears when the choice is checked:**<br>![checkbox_slot_example](https://user-images.githubusercontent.com/22588915/72614421-2a575e80-392a-11ea-928b-2d4ff30bf32f.gif) |
=> Add slot to "checkbox" component

vue/components/ui/atoms/dropdown/dropdown.stories.js, vue/components/ui/atoms/dropdown/dropdown.vue
| - | - |
| --- | --- |
| Issue |  Dropdown didn't had the default label based on the value key has the rest of the other components |
| Decisions | Make it equal to similar components |
=> Add dropdown default label based on value

vue/components/ui/molecules/modal/modal.vue
| - | - |
| --- | --- |
| Issue | Unused variable |
| Decisions |  Remove it |
=> Removed unnecessary variables

vue/components/ui/molecules/input-currency/assets/currencies.json, vue/components/ui/molecules/input-currency/input-currency.stories.js, vue/components/ui/molecules/input-currency/input-currency.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions |  Adds more currency symbols according to ISO standard currency codes (https://apps.cybersource.com/library/documentation/sbc/quickref/currencies.pdf); Fix value type to only accept numbers; Fix zero places - when a currency has zero places `return currencyInfo.places || fallback;` would always return `fallback` instead of `currencyInfo.places` holding the value 0. |
=> Currency update

vue/components/ui/atoms/container/container.stories.js, vue/components/ui/atoms/container/container.vue, vue/components/ui/organisms/listing/listing.stories.js, vue/components/ui/organisms/listing/listing.vue
=> Add expanded container mode

vue/components/ui/atoms/checkbox/checkbox.vue, vue/components/ui/molecules/filter/filter.stories.js, vue/components/ui/molecules/filter/filter.vue, vue/components/ui/molecules/table/table.vue, vue/components/ui/organisms/listing/listing.stories.js, vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Needed to fix problem with lazy loading |
| Decisions | • Added lazy loading support <br>• "listing" and "filter" components support the checkbox feature that was added to "table-ripe" |
=> Lazy loading in table and filter + listing checkboxes support 

vue/components/ui/molecules/alert/alert.vue
=> Add alert reset

vue/components/ui/atoms/input/input.stories.js, vue/components/ui/atoms/input/input.vue
| - | - |
| --- | --- |
| Issue | There was no type in the input, which is necessary for some simple validation, for example URLs. |
| Decisions | Added prop type. |
=> Type prop in input

vue/components/ui/atoms/input/input.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | On enter event emitted when enter is clicked in the input. Useful for certain situations, like PR [#24](https://github.com/ripe-tech/ripe-copper/pull/24)  |
=> Forward input keyup

vue/components/ui/atoms/checkbox/checkbox.stories.js, vue/components/ui/atoms/checkbox/checkbox.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | • Emit event in watch of "checkedData"<br>• Emit click event when checkbox is clicked |
=> Emit event in watch of "checkedData" and click event

vue/components/ui/molecules/announcements/announcements.vue
=> Announcements update checkbox usage

vue/components/ui/molecules/filter/filter.vue, vue/components/ui/molecules/table/table.vue, vue/components/ui/organisms/listing/listing.vue
Builds on top of https://github.com/ripe-tech/ripe-components-vue/pull/235
=> Improve dense table

vue/components/ui/organisms/listing/listing.vue
=> Add limit to listing

vue/components/ui/molecules/footer/footer.vue, vue/components/ui/organisms/listing/listing.vue
=> Add desktop footer padding

vue/components/ui/molecules/progress-bar/progress-bar.stories.js, vue/components/ui/molecules/progress-bar/progress-bar.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Added prop that allows to change the `progress-bar` component label alignment |
| Animated GIF | ![progress-bar_label_alignment](https://user-images.githubusercontent.com/22588915/74848865-fd82d680-532f-11ea-861f-19b33a954749.gif) |
=> Label alignment prop in "progress-bar" component

vue/components/ui/atoms/checkbox/checkbox.vue, vue/components/ui/atoms/index.js, vue/components/ui/atoms/radio/radio.vue, vue/components/ui/atoms/switcher/switcher.stories.js, vue/components/ui/atoms/switcher/switcher.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Switcher Component and respective story |
| Animated GIF | ![Feb-12-2020 12-30-37](https://user-images.githubusercontent.com/25725586/74335177-867b9a00-4d93-11ea-8c3d-b21461739fcc.gif) |
=> Switcher component

vue/components/ui/molecules/progress-bar/progress-bar.stories.js, vue/components/ui/molecules/progress-bar/progress-bar.vue
| - | - |
| --- | --- |
| Issue | - |
| Decisions | Progress bar is a lot smoother now |
| Animated GIF | **Before**![progress-bar_fill_before](https://user-images.githubusercontent.com/22588915/75139451-90cb5b80-56e4-11ea-84c4-b254d3594ead.gif) <br>**After this change**![progress-bar_fill_after](https://user-images.githubusercontent.com/22588915/75139455-92951f00-56e4-11ea-8d98-6c3421455e0c.gif) |
=> Smoother progress bar

vue/components/ui/atoms/breadcrumbs/breadcrumbs.stories.js, vue/components/ui/atoms/breadcrumbs/breadcrumbs.vue, vue/components/ui/atoms/index.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/issues/260 |
| Decisions | Created "breadcrumbs" component |
| Animated GIF | ![Breadcrumbs](https://user-images.githubusercontent.com/22588915/74746678-b3c9bb80-525d-11ea-9dc7-bbf93a8a0782.gif) |
=> #260 Created "breadcrumbs" component

vue/components/ui/atoms/dropdown/dropdown.stories.js, vue/components/ui/atoms/dropdown/dropdown.vue, vue/components/ui/molecules/select/assets/chevron-up.svg, vue/components/ui/molecules/select/select.stories.js, vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Added `direction` prop that allows the `select` to open upwards or downwards |
| Animated GIF | ![Components-Select_direction_up](https://user-images.githubusercontent.com/22588915/80080082-ff902e00-8548-11ea-9f72-3b9c26e12fb0.gif) |
=> Added direction prop to Select component

vue/components/ui/molecules/table/table.stories.js, vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Issue | |
| Decisions |Copy the template and the logic of ripe-white's [_table-ripe_](https://github.com/ripe-tech/ripe-white/blob/master/vue/components/molecules/table/table.vue) |
| Animated GIF | |
=> Update table-ripe component

vue/components/ui/atoms/button-icon/button-icon.vue
=> Fix button icon loading width

vue/components/ui/molecules/select/select.stories.js, vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/384 |
| Decisions | Added prop `autoScroll` which gives the ability for the `select` to auto scroll to the selected option when opening the dropdown |
| Animated GIF | ![Components-Select_auto_scroll](https://user-images.githubusercontent.com/22588915/81274536-58cb8780-9048-11ea-893c-bf33eb137e6f.gif) |
=> #384 Select auto scroll

vue/components/ui/atoms/dropdown/dropdown.stories.js, vue/components/ui/atoms/dropdown/dropdown.vue
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | Added selected props, which allow to specify which items in the dropdown are selected. Similar to the `ripe-white` dropdown. |
=> Selected props support

vue/components/ui/molecules/index.js, vue/components/ui/molecules/table-expandable/assets/arrow-down.svg, vue/components/ui/molecules/table-expandable/index.js, vue/components/ui/molecules/table-expandable/table-expandable.stories.js, vue/components/ui/molecules/table-expandable/table-expandable.vue, vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Decisions | Direct port from ripe-white. |
=> Port table-expandable from ripe-white

vue/components/ui/molecules/table/table.vue
=> Improve table click and hover

vue/components/ui/molecules/tabs/tabs.vue
| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-components-vue/issues/319 |
| Decisions | Backports the addition of semantic classes from RIPE White. |
=> Backport tab classes

package.json, vue/test/base.js, vue/test/components/tag/tag.test.js, vue/test/mocks/index.js, vue/test/mocks/mixins/device.js, vue/test/mocks/mixins/index.js, vue/test/setup.js, vue/test/webpack.config.js
| - | - |
| --- | --- |
| Decisions | Copied from RIPE Pulse. |
=> First unit test

vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/issues/294 |
| Dependencies | https://github.com/ripe-tech/ripe-components-vue/pull/297 |
| Decisions | Updated `listing` component to support the new changes in `container-ripe` |
| Animated GIF | **Before this change:**<br><img width="1003" alt="imagem" src="https://user-images.githubusercontent.com/22588915/81719156-98dda080-9474-11ea-8348-d48f92d58059.png"><img width="390" alt="imagem" src="https://user-images.githubusercontent.com/22588915/81720119-dc84da00-9475-11ea-9ebe-5845322cbec4.png"><br><br>**After this change:**<br><img width="1003" alt="imagem" src="https://user-images.githubusercontent.com/22588915/81719062-777cb480-9474-11ea-9579-bc64fbf55dbe.png"><img width="390" alt="imagem" …
=> #294 Updated "listing" component after "container-ripe" changes

vue/test/components/tag/tag.test.js
| - | - |
| --- | --- |
| Decisions | Fix test descriptions to be in accordance to conventions. |
=> Fix unit test description

vue/test/components/select/select.test.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/pull/252 |
| Decisions | Add selector tests as suggested in https://github.com/ripe-tech/ripe-components-vue/pull/252#issuecomment-644160963 |
=> Add select unit tests

vue/components/ui/atoms/dropdown/dropdown.stories.js, vue/components/ui/atoms/dropdown/dropdown.vue, vue/components/ui/molecules/select/select.stories.js
| - | - |
| --- | --- |
| Decisions | Ported from `ripe-white` |
=> Port dropdown and select changes from ripe-white

vue/components/ui/atoms/tag/tag.vue
| - | - |
| --- | --- |
| Decisions | Port from https://github.com/ripe-tech/ripe-white/commit/5d1bd4b921658cc5d4aa18dc60e1a53751774f3c |
=> Port tags changes

vue/components/ui/molecules/table/table.stories.js
| - | - |
| --- | --- |
| Decisions | Removes undefined variable. |
=> Fix table storybook

vue/components/ui/atoms/dropdown/dropdown.vue
| - | - |
| --- | --- |
| Decisions | Add semantic classes to dropdown items to allow automated testing. |
=> Add semantic classes to dropdown items

vue/components/ui/atoms/dropdown/dropdown.vue
Reverts ripe-tech/ripe-components-vue#342
=> Revert "Add semantic classes to dropdown items"

vue/components/ui/atoms/avatar/avatar.stories.js, vue/components/ui/atoms/avatar/avatar.vue
| - | - |
| --- | --- |
| Dependencies | Backport https://github.com/ripe-tech/ripe-white/pull/516/files |
=> Backport avatar (very-large size)

vue/components/ui/molecules/upload-area/upload-area.vue
| - | - |
| --- | --- |
| Decisions | Add backport from https://github.com/ripe-tech/ripe-white/pull/520 |
=> Backport enhace upload area

vue/components/ui/molecules/avatar-name/avatar-name.stories.js, vue/components/ui/molecules/avatar-name/avatar-name.vue, vue/components/ui/molecules/index.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-registry/issues/1 |
| Decisions | Created component `avatar-name` |
| Animated GIF | ![avatar-name](https://user-images.githubusercontent.com/22588915/91824250-6083ed00-ec32-11ea-9e0a-bddb4a5bac3a.gif) |
=> Added component "avatar-name"

vue/components/ui/molecules/filter/filter.vue, vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Decisions | Make sorting in dynamic tables configurable. |
=> Add default sort prop to tables

vue/components/ui/molecules/form-input/form-input.stories.js, vue/components/ui/molecules/form-input/form-input.vue
| - | - |
| --- | --- |
| Decisions | Backport of https://github.com/ripe-tech/ripe-white/pull/577 |
=> Form Input alignment

package.json, vue/test/base.js, vue/test/setup.js, vue/test/webpack.config.js
=> Support for polyfill

vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue | Fixes https://github.com/ripe-tech/ripe-pulse/issues/156 |
| Animated GIF | ![](http://g.recordit.co/bscmH2sNPb.gif) |
=> #156: Fix listing search in mobile

vue/components/ui/atoms/container/container.vue, vue/components/ui/molecules/form-buttons/form-buttons.stories.js, vue/components/ui/molecules/form-buttons/form-buttons.vue, vue/components/ui/molecules/form-buttons/index.js, vue/components/ui/molecules/index.js, vue/components/ui/organisms/form/form.stories.js, vue/components/ui/organisms/form/form.vue, vue/components/ui/organisms/index.js
| - | - |
| --- | --- |
| Animated GIF | ![](http://g.recordit.co/qoYb5UHCfl.gif) |
=> Generic form component

vue/components/ui/atoms/container/container.vue, vue/components/ui/molecules/form-buttons/form-buttons.stories.js, vue/components/ui/molecules/form-buttons/form-buttons.vue, vue/components/ui/molecules/form-buttons/index.js, vue/components/ui/molecules/index.js, vue/components/ui/organisms/form/form.stories.js, vue/components/ui/organisms/form/form.vue, vue/components/ui/organisms/index.js
Restore the elements back to the branch
=> Revert "Revert "Generic form component""

vue/components/ui/molecules/avatar-name-email/avatar-name-email.stories.js, vue/components/ui/molecules/avatar-name-email/avatar-name-email.vue, vue/components/ui/molecules/index.js
| - | - |
| --- | --- |
| Issue | Multiple pages have the pattenr of avatar followed by name and email: <br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fd873a8666bc56f6e73<br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fd8b7f9a16b8697c0eb<br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fd5d3b54f86278616a1<br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fd5defb668756113a2d<br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fd718633c7a16f5c8c8<br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fd885fde476f125276f<br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/5f194fd9b7f9a16b8697c17d<br>https://app.zeplin.io/project/5db732f9c02f1e8327288741/screen/ …
=> Created "avatar-name-email" component

js/index.js, js/util.js, vue/components/ui/molecules/tabs/tabs.vue, vue/components/ui/organisms/form/form.vue, vue/mixins/utils.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/pull/378#issuecomment-702214987 |
| Decisions | • Added `buildSlug` method <br>• Added semantic classes to column, section and form input <br>• Improved tabs classes |
=> Added semantic classes

vue/components/ui/organisms/entity-shower/entity-shower.stories.js, vue/components/ui/organisms/entity-shower/entity-shower.vue
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | https://github.com/ripe-tech/ripe-components-vue/pull/383 |
| Decisions | • Created `entity-shower` storybook story <br>• Documented `entity-shower` props |
| Animated GIF | ![Captura de ecrã 2020-10-08 às 11 33 50](https://user-images.githubusercontent.com/22588915/95447767-2953da80-095a-11eb-87d6-e73254adf4a9.png) |
=> Entity shower story and documentation

.storybook/addons.js, .storybook/main.js, .storybook/preview.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/600 |
| Decisions | See https://github.com/ripe-tech/ripe-white/pull/604 |
=> #600: Fix storybook deprecated configs

vue/components/ui/organisms/entity-editor/entity-editor.stories.js, vue/components/ui/organisms/entity-editor/entity-editor.vue
| - | - |
| --- | --- |
| Issue | -- |
| Dependencies | https://github.com/ripe-tech/ripe-components-vue/pull/382 |
| Decisions | • Created `entity-editor` storybook story <br>• Documented `entity-editor` props |
| Animated GIF | ![entity-editor_story](https://user-images.githubusercontent.com/22588915/95483081-b57bf700-0986-11eb-8b10-96aaee1f533a.gif) |
=> Entity editor story and documentation

package.json
| - | - |
| --- | --- |
| Issue | `npm run test-watch:vue` is currently failing. |
| Decisions | Fix vue test watch script name.|
=> Fix test watch script

vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.stories.js, vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue, vue/components/ui/molecules/index.js, vue/test/components/button-icon-toggle/button-icon-toggle.test.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/217 |
| Decisions | Add button icon toogle based on button-icon component to add internal value toggle logic. |
| Animated GIF | ![b](https://user-images.githubusercontent.com/24736423/98391529-adc77500-204e-11eb-9800-f1bf2c0c1db2.gif) |
=> #217 Button icon toggle

.storybook/preview.js, vue/components/ui/molecules/carousel/carousel.stories.js, vue/components/ui/molecules/carousel/carousel.vue, vue/components/ui/molecules/index.js, vue/test/components/carousel/carousel.test.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/2 |
| Decisions | Add lite version of carousel with tests and documentation. |
| Animated GIF | ![Peek 2021-01-08 12-23](https://user-images.githubusercontent.com/24736423/104015306-53f93d80-51ac-11eb-9bc6-effed19fa3f3.gif)  |
=> #2 Add carousel

vue/components/ui/molecules/carousel/carousel.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/2 |
| Decisions | Change mouse cursor pointer to grabbing to improve the user experience. |
| Animated GIF | ![Peek 2021-01-15 14-24](https://user-images.githubusercontent.com/24736423/104738511-89b69d00-573d-11eb-90ec-d10cef18fcd5.gif) |
=> #2 Improve carousel's cursor pointer to grabbing

vue/components/ui/atoms/rich-textarea/rich-textarea.vue
| - | - |
| --- | --- |
| Decisions | Turn it off by default given it does nothing (either in FE or in any BE). |
=> feat: turn smile off by default

vue/components/ui/molecules/table/table.vue
| - | - |
| --- | --- |
| Animated GIF | ![](http://g.recordit.co/ZZXjWxse7X.gif) |
=> feat: sticky table header

vue/components/ui/atoms/rich-textarea/rich-textarea.vue, vue/components/ui/organisms/chat/chat.vue
| - | - |
| --- | --- |
| Decisions | Using a pessimistic or an optimistic approach can be defined by how `sendMessage` is implemented by the client. |
=> feat: blocking send message on chat

vue/components/ui/organisms/index.js, vue/components/ui/organisms/input-list/input-list.stories.js, vue/components/ui/organisms/input-list/input-list.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/issues/410 |
| Decisions | Add input list with logic based of [form](https://github.com/ripe-tech/ripe-components-vue/blob/a03e5314a19beef0c126146f499d5aa373fbd3f6/vue/components/ui/organisms/form/form.vue). |
| Animated GIF | ![image](https://user-images.githubusercontent.com/24736423/109136705-4f82e700-7750-11eb-96d3-e68b13454bd9.png) |
=> #410 Input List

vue/components/ui/molecules/carousel/carousel.stories.js, vue/components/ui/molecules/carousel/carousel.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-twitch/issues/39#issuecomment-792724138 |
| Decisions | - Add carousel slide animation. <br> - Having responsive size behavior by default instead of hardcoded width and heights as suggested by https://github.com/ripe-tech/ripe-twitch-ui/pull/106#discussion_r589344468 |
| Animated GIF | ![Peek 2021-03-08 18-21](https://user-images.githubusercontent.com/24736423/110364016-2fe69b00-803b-11eb-874a-0e76554b39f5.gif) |
=> #39 Carousel swipe animation

vue/components/ui/atoms/image-item/image-item.stories.js, vue/components/ui/atoms/image-item/image-item.vue, vue/components/ui/atoms/index.js, vue/components/ui/molecules/image-list/image-list.stories.js, vue/components/ui/molecules/image-list/image-list.vue, vue/components/ui/molecules/index.js
| - | - |
| --- | --- |
| Issue | Related to https://github.com/ripe-tech/ripe-twitch-admin-ui/pull/3 and https://github.com/ripe-tech/ripe-util-vue/issues/38 |
| Decisions | Components for showing a list of images. Allows for image highlight, button in the top right corner and click on image events. |
| Links | - https://ripe-components-vue-git-ms-image-listing-component-platforme.vercel.app/?path=/story/components-atoms-image-item--image-item<br> - https://ripe-components-vue-git-ms-image-listing-component-platforme.vercel.app/?path=/story/components-molecules-image-list--image-list |
| Animated GIF | `image-item`: <br> ![image-item](https://user-images.githubusercontent.com/25725586/111601531-5be7e600-87ca-11eb-911a-921d543d6b96.gif)<br> `image-list`: …
=> feat: image listing components

js/config.js
| - | - |
| --- | --- |
| Decisions | Based on https://github.com/ripe-tech/ripe-white/commit/1de304af436c984ed0127d5f7e68d9fb1448a1d8 |
=> feat: fallback support for hasFeature

vue/components/ui/organisms/form/form.vue
| - | - |
| --- | --- |
| Decisions | Used by https://github.com/ripe-tech/ripe-white-admin-ui/pull/46 |
=> feat: add list input to form

vue/components/ui/organisms/entity-show/entity-show.stories.js
| - | - |
| --- | --- |
| Decisions | Small fix storybook story structure for entity show. |
=> Fix storybook structure

CHANGELOG.md, vue/components/ui/molecules/select-checkboxes/select-checkboxes.stories.js, vue/components/ui/molecules/select-checkboxes/select-checkboxes.vue
| - | - |
| --- | --- |
| Issue | Motivated by an ad-hoc implementation in https://github.com/ripe-tech/ripe-util-vue/pull/53 |
| Animated GIF | ![](http://g.recordit.co/EhxBgZ0II3.gif) |
=> feat: all option in select-checkboxes

package.json
| - | - |
| --- | --- |
| Issue | -- |
| Decisions | The regressions were fixed and a new release of vue-test-utils was made: https://github.com/vuejs/vue-test-utils/releases/tag/v1.2.0 <br> Will also change for ripe-white |
=> feat: use latest vue-test-utils version

.storybook/main.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/issues/XXX |
| Decisions | Solution from [here](https://github.com/storybookjs/storybook/issues/14342#issuecomment-811081265) |
=> fix: new storybook 'stories' format to fix watch getting constantly triggering build

vue/components/ui/organisms/input-list/input-list.stories.js, vue/components/ui/organisms/input-list/input-list.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-components-vue/pull/491#issuecomment-840683434 |
=> refactor: input list add button position

CHANGELOG.md, vue/components/ui/atoms/container/container.stories.js, vue/components/ui/atoms/container/container.vue, vue/components/ui/organisms/listing/listing.stories.js
| - | - |
| --- | --- |
| Animated GIF | ![](http://g.recordit.co/yzPhzqnZKs.gif) |
=> feat: inline container and listing

vue/mixins/config.js, vue/mixins/utils.js
| - | - |
| --- | --- |
| Issue | Need to pass options to normalize method |
| Decisions | Update `ripe-commons` methods arguments |
=> Update ripe-commons methods arguments

vue/components/ui/molecules/modal/modal.vue
| - | - |
| --- | --- |
| Decisions | - Remove dead computed variable [after classes refactor](https://github.com/ripe-tech/ripe-components-vue/commit/1dbf7697a0cd8d5815c94a9633ec0f81df98714a#diff-3becf7bb7d029127ef5823d97c9dabd79edac1ffeaa87e945372a02518486c09). |
=> Modal: clean dead code

vue/components/ui/atoms/input/input.vue, vue/components/ui/molecules/calendar/calendar.stories.js, vue/components/ui/molecules/calendar/calendar.vue, vue/components/ui/molecules/index.js, vue/components/ui/molecules/input-date/input-date.stories.js, vue/components/ui/molecules/input-date/input-date.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/316#issuecomment-851534607 |
| Decisions | - Add `onclick` and `keydown` emit handlers for `<input>` <br> - Add calendar single date picker component. <br> - Using native input with reactive state setter. |
| Animated GIF |  ![Peek 2021-05-31 16-08](https://user-images.githubusercontent.com/24736423/120213167-cf768c80-c22a-11eb-9311-ddbf7a73a47e.gif) |
=> #316 Calendar original design

CHANGELOG.md, vue/components/ui/molecules/notification/notification.stories.js, vue/components/ui/molecules/notification/notification.vue
| - | - |
| --- | --- |
| Decisions | |
| Animated GIF | ![aEDQrfuqCa](https://user-images.githubusercontent.com/8842023/124938065-e1a0d300-dfff-11eb-84d1-eb718fa394f6.gif)|
=> feat: add link to notification component

CHANGELOG.md, package.json
This is blocking: https://github.com/ripe-tech/ripe-util/issues/72#issuecomment-885516928
=> version: 0.13.1

CHANGELOG.md, vue/components/ui/templates/error-part/error-part.vue, vue/mixins/part.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/pull/124#issuecomment-863971011 |
| Decisions | - Add home page button. <br> - Fix home redirect for nuxt.js. |
| Animated GIF | <img width="1278" alt="image" src="https://user-images.githubusercontent.com/24736423/122594090-78601c80-d05e-11eb-944b-67c0ca834fa1.png"> |
=> Error page: add navigate home button

CHANGELOG.md, vue/components/ui/molecules/button-toggle/button-toggle.stories.js, vue/components/ui/molecules/button-toggle/button-toggle.vue, vue/components/ui/molecules/index.js, vue/components/ui/organisms/button-group/button-group.stories.js, vue/components/ui/organisms/button-group/button-group.vue, vue/components/ui/organisms/index.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/99 |
| Decisions | • Button toggle component <br> • Button group toggle |
| Animated GIF | ![button-group](https://user-images.githubusercontent.com/25725586/122431441-5dbd7300-cf8c-11eb-8a62-b4ef32d8cdcd.gif)![button-toggle](https://user-images.githubusercontent.com/25725586/122431446-5e560980-cf8c-11eb-9ce0-e9a6407fcbb6.gif)|
=> #99: Button group component

CHANGELOG.md, vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Decisions | - Add search clear prop |
https://user-images.githubusercontent.com/24736423/133245307-c4db2fa6-a1cf-4b52-909b-6ce9c387c62c.mov
=> Listing: clear search

CHANGELOG.md, package.json
Related issue: https://github.com/ripe-tech/ripe-core/issues/4659
=> version: 0.19.0

CHANGELOG.md, vue/components/ui/atoms/dropdown/dropdown.stories.js, vue/components/ui/atoms/dropdown/dropdown.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/281 |
| Decisions | Add disabled option to [follow design](https://www.figma.com/file/RoRe364gBaey04nvKh9Syt/RIPE-Pulse---Public?node-id=1008%3A9048) |
| Animated GIF (Pulse) | ![pulse-bulk-status-disabled](https://user-images.githubusercontent.com/16060539/156156607-362b591f-e610-4b6f-bebc-9c8628536213.gif) |
=> feat: disabled items for dropdown component

vue/components/ui/molecules/tooltip/tooltip.stories.js, vue/components/ui/molecules/tooltip/tooltip.vue
Improved feature set for tooltips
=> Improved feature set for tooltips

CHANGELOG.md, package.json
| - | - |
| --- | --- |
| Issue | Deployment of new version (related: https://github.com/ripe-tech/ripe-util-vue/issues/257 and https://github.com/ripe-tech/ripe-util-vue/issues/265 ) |
| Decisions | Updated changelog and `package.json` version |
=> Version: 0.21.0

CHANGELOG.md, vue/components/ui/atoms/entry/entry.stories.js, vue/components/ui/atoms/entry/entry.vue, vue/components/ui/atoms/index.js
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/316 |
| Decisions | Add `entry` component (related: https://github.com/ripe-tech/ripe-pulse/pull/330#issuecomment-1094962172) |
https://user-images.githubusercontent.com/22588915/162736944-576f3f09-d13f-4017-99e6-dfb7a7e9b505.mov
=> #316 Add `entry` component

CHANGELOG.md, vue/components/ui/atoms/dropdown/dropdown.vue, vue/components/ui/molecules/select-checkboxes/select-checkboxes.stories.js, vue/components/ui/molecules/select-checkboxes/select-checkboxes.vue, vue/components/ui/molecules/select/select.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/270 |
| Decisions | Add search bar to `select-checkboxes` |
https://user-images.githubusercontent.com/22588915/163013102-e0a73982-4db8-43f0-8f56-066099d51a94.mp4
=> #270 `select-checkboxes` search bar

CHANGELOG.md, package.json
| - | - |
| --- | --- |
| Issue | Deployment of new version (related: https://github.com/ripe-tech/ripe-pulse/issues/316 and https://github.com/ripe-tech/ripe-util-vue/issues/270) |
| Decisions | Updated changelog and `package.json` version |
=> Version: 0.22.0

CHANGELOG.md, vue/components/ui/molecules/avatar-list/avatar-list.stories.js, vue/components/ui/molecules/avatar-list/avatar-list.vue, vue/components/ui/molecules/index.js
| - | - |
| --- | --- |
| Issue | #571 |
| Decisions | Create a new component that groups avatars, with a max value. If the number of avatars exceeds the maximum number of values, a new circle will show the amount of missing elements. |
Here's how it was supposed to look design and feature wise: 
https://user-images.githubusercontent.com/22790704/164028184-df71eb47-b3cf-43a6-b35c-5350b13ff81e.mov
Here's the current state of the PR:
https://user-images.githubusercontent.com/22790704/164028724-45fab0d9-e253-49a4-849a-6eaed31f7a99.mov
=> #571 - Add Avatar List Component

CHANGELOG.md, vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-util-vue/issues/288 |
| Decisions |Add better loading style for other colors <br> Remove hover and interaction while loading <br>|
| Animated GIF |![](http://g.recordit.co/90MG7lowTP.gif)|
=> #288 button-color loading improvements

CHANGELOG.md, vue/components/ui/molecules/index.js, vue/components/ui/molecules/pagination/index.js, vue/components/ui/molecules/pagination/pagination.stories.js, vue/components/ui/molecules/pagination/pagination.vue
| - | - |
| --- | --- |
| Issue | [ripe-util-vue/#307](https://github.com/ripe-tech/ripe-util-vue/issues/307) |
| Decisions | Migrate `pagination` component from [ripe-white](https://github.com/ripe-tech/ripe-white/tree/master/vue/components/molecules/pagination) |
| Animated GIF | ![nVWubtB2jy](https://user-images.githubusercontent.com/8842023/188429158-6a4e3bfc-966e-4932-8fbf-0ce5ad17d227.gif)|
=> feat: add `pagination` component

CHANGELOG.md, package.json
* Reactivity to `emptySlots()` computed property in `molecules/upload-area.vue` 
*
* `upload-area` component not clearing data - [#612](https://github.com/ripe-tech/ripe-components-vue/issues/612)
* Fix `@vue/test-utils` version to avoid breaking changes
=> version: `0.23.3`

CHANGELOG.md, vue/components/ui/atoms/button-color/button-color.stories.js, vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Decisions | * Added `transparent` color to the storybook as it is currently seeing some use.<br>* Added unused style. <br> * Removed unnecessary style that was breaking some interactions.|
| Animated GIFs |Before ![](https://user-images.githubusercontent.com/10127604/200178526-953256a8-f6eb-40f3-90f3-c9db5f768112.gif) After ![](https://user-images.githubusercontent.com/10127604/200178523-1070a06b-e63c-4d20-b5f2-8d5a16a75fdf.gif)|
=> button-color improvements

CHANGELOG.md, package.json
* Fixed some interactions for `button-color` in `white` and `transparent` colors
* Fixed `noFileSelected()` computed property to handle `null` values and consequently adapt `emptySlots()` computed property
=> version: `0.23.4`

CHANGELOG.md, vue/components/ui/atoms/button-color/button-color.vue
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/357 |
| Dependencies | - |
| Decisions |- This regression was caused when we [added](https://github.com/ripe-tech/ripe-components-vue/pull/584/files) `iconPosition` prop |
| Animated GIF | <img width="1333" alt="Screenshot 2022-12-05 at 17 03 02" src="https://user-images.githubusercontent.com/8842023/205699488-547c4c1b-4d8f-4ec4-a873-1dcfe0a5ae4f.png">|
=> fix: view on white button

CHANGELOG.md, vue/components/ui/organisms/listing/listing.vue
| - | - |
| --- | --- |
| Issue |https://github.com/ripe-tech/ripe-pulse/issues/240 |
| Decisions |* Add method to replace filter and specify operator on `listing` <br>* Add method to remove filters on `listing` |
=> #240 Filter orders

CHANGELOG.md, package.json
* Add method to replace filter and specify operator on `listing` - [ripe-pulse/#240](https://github.com/ripe-tech/ripe-pulse/issues/240)
* Add method to remove filters on `listing` - [ripe-pulse/#240](https://github.com/ripe-tech/ripe-pulse/issues/240)
* Regression on view on white button - [ripe-pulse/#357](https://github.com/ripe-tech/ripe-pulse/issues/357)
=> version: 0.23.5

CHANGELOG.md, package.json
* Add `setSearchFilter` method - [ripe-pulse/#240](https://github.com/ripe-tech/ripe-pulse/issues/240)
* Fix `addFilter` for when the filter is empty - [ripe-pulse/#240](https://github.com/ripe-tech/ripe-pulse/issues/240)
=> version: 0.23.6

CHANGELOG.md, package.json, vue/components/ui/organisms/listing/listing.vue
closes itself
- None
- titlePrefix default needs to be empty
- None
=> change title prefix default

CHANGELOG.md, vue/components/ui/molecules/lightbox/lightbox.stories.js, vue/components/ui/molecules/lightbox/lightbox.vue
- https://github.com/ripe-tech/ripe-components-vue/issues/635
Add props:
- title
- subtitle
=> 635 - add title and subTitle props to lightbox

CHANGELOG.md, vue/components/ui/atoms/input/input.stories.js, vue/components/ui/atoms/input/input.vue
- https://github.com/ripe-tech/ripe-components-vue/issues/638
- add backgroundColor to input component
=> 638 - add backgroundColor to input component

CHANGELOG.md, vue/components/ui/atoms/input/input.stories.js, vue/components/ui/atoms/input/input.vue, vue/components/ui/molecules/section-expandable/section-expandable.stories.js, vue/components/ui/molecules/section-expandable/section-expandable.vue
- https://github.com/ripe-tech/ripe-components-vue/issues/641
- 641 - add tiny as part of size prop in section expandable component
=> 641 - add tiny as part of size prop
